### ISSUE TITLE
package_r_2_15_0: libreadline.so.6 error

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-devteam#100]
When tools (e.g. MACS14) attempt to use R from this package, I get an error regarding libreadline.so.6. This is on a CentOS5 system.  I can reproduce the error attempting to run R from the command line. Perhaps the LDFLAGS weren't set correctly when the binaries were built?

```
> source ./tool-dependencies/R/2.15.0/devteam/package_r_2_15_0/6c34eaa82fed/env.sh
> R
> R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
```

**Comment by erasche** [comment]
devteam see https://github.com/galaxyproject/tools-iuc/issues/101

**Comment by blankenberg** [comment]
ping @davebx

**Comment by lparsons** [comment]
Any update on this? I've got a number of tools failing on my Galaxy instance due to this problem (Summary_Statistics1 is another).

**Comment by bgruening** [comment]
@lparsons is this still an issue?

**Comment by lparsons** [comment]
@bgruening Yes, this is still an issue. I'm not aware of anything that has changed, but I'd be happy to test something if there is something to test.

**Comment by bernt-matthias** [comment]
I guess this is not an issue nowadays anymore.
