### ISSUE TITLE
Move samtool_filter2

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-devteam#108]
Should we move samtool_filter2 to the other samtools wrapper? Would be worth to update it and stick it into a samtools suite. Comments? @nekrut ?

**Comment by nsoranzo** [comment]
:+1:

I've done a preliminary cleanup in PR #110, should work as it is also with Samtools 1.2 . It may be a good time to correct the tool id and filename (i.e. `s/samtool/samtools/`).

**Comment by bgruening** [comment]
+1 for fixing the tool id and repository name :)

**Comment by nsoranzo** [comment]
Moreover, we may also move `tools/sam_bitwise_flag_filter/sam_bitwise_flag_filter.xml` to `legacy/`.

**Comment by bernt-matthias** [comment]
samtools is now at IUC. So I guess this can be closed.
