### ISSUE TITLE
samtools_phase tests fail

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-devteam#113]
when I run planemo test (using samtools 1.2) on this tool https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/samtools/samtools_phase

I get this test error report: www.googledrive.com/host/0BycJJtbagAMTd2V2UzVURDRRQUE

ping @nekrut

**Comment by nekrut** [comment]
this tool SHOULD not go to main

**Comment by martenson** [comment]
I will make sure it will not. However if it should go to Tool Shed it should pass tests.

**Comment by bernt-matthias** [comment]
Samtools now at IUC
