### ISSUE TITLE
samtools_stats tests fail

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-devteam#114]
planemo run test report:
www.googledrive.com/host/0BycJJtbagAMTQThZdlI2VXAySm8

ping @nekrut

**Comment by nekrut** [comment]
I cannot open this link

**Comment by martenson** [comment]
fixed

**Comment by bgruening** [comment]
@martenson this seems to be because you are running it with `1.2+htslib-1.2` and @nekrut with `1.2+htslib-1.2.1`.

**Comment by martenson** [comment]
@bgruening I thought these two lines will be ignored because of `lines_diff="2"`

**Comment by bgruening** [comment]
Not sure, if you have a test environment, can you try to increase to 3?

**Comment by jmchilton** [comment]
I think it needs to be 4 - 2 for each line of diff :(

**Comment by martenson** [comment]
@jmchilton yeah I just read something in wiki that would advocate that, testing now

**Comment by martenson** [comment]
`## files diff on /Users/marten/devel/git/tools-devteam/tool_collections/samtools/samtools_stats/test-data/samtools_stats_out1.tab and /var/folders/2z/ntdb9g2n7tq6_bcq4dj9hj9r0000gn/T/tmpgz2VbR/tmp/tmpOtrcwqsamtools_stats_out1.tab lines_diff=2, found diff = 4`

I will fix this.

**Comment by martenson** [comment]
fixed in 814255bf7c326d4f872c3fafaffdb4b794c5245c

**Comment by bgruening** [comment]
Ah yes 4 - this always confuses me. Thanks Martin for fixing!
