### ISSUE TITLE
Tools are missing owned by devteam in the Test Tool Shed

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-devteam#116]
* [ ] [FASTQ to FASTA converter](https://toolshed.g2.bx.psu.edu/view/devteam/tabular_to_fastq)
* [ ] FASTQ Masker
* [ ] Combine FASTA and QUAL into FASTQ
* [ ] FASTQ Trimmer (by column)
* [ ] FASTQ Summary Statistics
* [ ] Manipulate FASTQ
* [ ] Filter FASTQ

**Comment by nsoranzo** [comment]
Missing from the Test Tool Shed or from this repository?

**Comment by bgruening** [comment]
In this repository it's missing.

**Comment by nsoranzo** [comment]
Look in tool_collections/galaxy_sequence_utils/ .

**Comment by bgruening** [comment]
Upps, good to know. Thanks!
