### ISSUE TITLE
clustalw tool outputs in 2 unknown data format

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/tools-devteam#117]
In file https://github.com/galaxyproject/tools-devteam/blob/master/tools/clustalw/rgClustalw.xml#L68 `clustal` and `phylip` are used as possible output formats, but are not defined either in Galaxy or in this tool repository.

**Comment by bgruening** [comment]
@nsoranzo is this defined in `emboss_datatypes`?

**Comment by nsoranzo** [comment]
Yes, both. So, should we add a repository dependency on `emboss_datatypes`?

**Comment by bgruening** [comment]
Yes please! Or even better, sneak this into Galaxy! If you back me up I will try to create a PR :)

**Comment by peterjc** [comment]
+1 on adding these formats to Galaxy directly.

**Comment by bgruening** [comment]
Ok I will do this later today.

**Comment by nsoranzo** [comment]
Sure, even better.

**Comment by blankenberg** [comment]
xref https://github.com/galaxyproject/galaxy/pull/148

**Comment by nsoranzo** [comment]
Should I add the repository dependency in the mean time? I don't think that will harm, and will be useful for people with "old" Galaxy releases.

**Comment by bgruening** [comment]
Yes please do so: But this was a good opportunity to get the datatype discussion started again: https://github.com/galaxyproject/galaxy/pull/148
