### ISSUE TITLE
Linting Issues

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-devteam#120]
- [ ] Repository names must contain only lower-case letters, numbers and underscore (tools/cummeRbund)
- [ ] all kraken repos use a readme.md, which is not supported.

**Comment by erasche** [comment]
xref https://travis-ci.org/galaxyproject/tools-devteam/builds/59901506

**Comment by jmchilton** [comment]
All this GitHub traffic today and I almost didn't see this. Awesome, thanks for the fixes!

**Comment by erasche** [comment]
Proper xref: https://github.com/galaxyproject/tools-devteam/pull/121
