### ISSUE TITLE
${static_path} should not be used?

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/tools-devteam#126]
For example, bamtools filter uses images in the documentation but the url is not properly constructed:
```html
  ﻿﻿<img alt="/repository/static/images/59bc5dbe6dfc6d4c//static%2Fimages%2Fsingle-filter.png" src="/repository/static/images/59bc5dbe6dfc6d4c//static%2Fimages%2Fsingle-filter.png">
```
Removing `static%2Fimages%2F` shows the image properly. Also when installed this `static%2Fimages%2F` should be removed to be able to show the image. 

Removing `${static_path}` from the .xml solves the issue. Also, the documentation has no mentioning of this and the way stated in the documentation just works (https://wiki.galaxyproject.org/DefiningImagesInToolConfigs).
    .. image:: single-filter.png

Note: `static_enabled = False/True` does not seem to have any effect on this

**Comment by bgruening** [comment]
@scholtalbers true. Didn't know about the `${static_path}`. @blankenberg is there any other reason `.. image:: single-filter.png` is not used? Can we change this?

**Comment by bgruening** [comment]
@scholtalbers can you test the PR? Thanks!

**Comment by scholtalbers** [comment]
@bgruening any reason for choosing the deprecated "$PATH_TO_IMAGES"? (see wiki ;) ). In addition, I'm trying to test this, but with a clean galaxy install (or planemo serve) I cannot get any variation of the image tag to work - this is supposed to work even without a toolshed installation right? ( I just got back from vacation so it might be something I overlooked..)

**Comment by bgruening** [comment]
@scholtalbers no sorry, was not aware of the deprecation. For me this works, but only from TS installations as I remember correctly. Can you get this right? Or should I do this?

**Comment by martenson** [comment]
this is behaving really weird; without the prefix it won't find the file unless it is in root however even if it is in the images/ folder the root link to it will still work
ping @blankenberg

**Comment by martenson** [comment]
I  just moved all the images in bamtools_filter to `bamtools_filter/random_folder/raaandom/images` and the root links are still working (http://127.0.0.1:8080/galaxy/admin_toolshed/static/images/36ddb788a0f14eb3/multiple-filters.png)

**Comment by martenson** [comment]
the route uses wildcard to consume everything before repository_id and filename
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/buildapp.py#L537
however I still do not know how is it actually resolving everything to root

**Comment by martenson** [comment]
related https://github.com/galaxyproject/tools-devteam/pull/212

**Comment by martenson** [comment]
I think this is resolved with https://github.com/galaxyproject/galaxy/pull/660
