### ISSUE TITLE
weblogo3 tool fails when "Text" output format is selected

### ISSUE THREAD

**Issue by bcclaywell** [galaxyproject/tools-devteam#141]
The weblogo3 tool is failing with the following generic error on Galaxy Main (as well as our local instance) when the "Text" output format is selected:

```
## rgWebLogo3.py error - executing weblogo -F txt -c auto -o /galaxy-repl/main/files/011/411/dataset_11411895.dat -U bits -t "Galaxy-Rgenetics Sequence Logo" -f /galaxy-repl/main/files/011/411/dataset_11411891.dat -s large returned error code 2
## This may be a data problem or a tool dependency (weblogo) installation problem
## Please ensure weblogo is correctly installed and working on the command line -see http://code.google.com/p/weblogo
```

On our instance I replicated the job environment and ran `weblogo` by hand:

```
$ weblogo -F txt -c auto -o output.dat -U bits -t "Galaxy-Rgenetics Sequence Logo" -f dataset_8485.dat -s large
Usage: weblogo [options]  < sequence_data.fa > sequence_logo.eps

weblogo: error: option -F: invalid choice: 'txt' (choose from 'svg', 'eps', 'jpeg', 'pdf', 'png_print', 'logodata', 'png')
```

It looks like the `option` tag for text output in `rgWebLogo3.xml` should have the `value` attribute `logodata` rather than `txt`.

As an aside, debugging issues with this tool (see also #65) is made more difficult by the omission of `weblogo`'s stdout/stderr in the error message. That output *is* captured and stored, but is not included in the error message before the early call to `sys.exit` in the `rgWebLogo3.runCL` function.

**Comment by bgruening** [comment]
@bcclaywell hope this will fix your issue. Sorry for being so slow and thanks for your bug report!

**Comment by martenson** [comment]
thank you for the report @bcclaywell and for the fix @bgruening
