### ISSUE TITLE
Snyc COMMENT tags between picard tools

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-devteam#150]
Sync the behaviour of `picard_FastqToSam.xml`, `picard_MarkDuplicatesWithMateCigar.xml` and `picard_AddCommentsToBam.xml`, `picard_MarkDuplicates.xml` and `picard_MergeSamFiles.xml` in `COMMENT` handling.

See: https://github.com/galaxyproject/tools-devteam/pull/149

**Comment by bernt-matthias** [comment]
Seems fixed. And tools are now at IUC anyway...
