### ISSUE TITLE
tool_data_table_conf definition for a number of vcflib tools

### ISSUE THREAD

**Issue by afgane** [galaxyproject/tools-devteam#156]
Is the `.sample` definition for `tool_data_table_conf.xml` wrong in a number of vcflib tools, for example https://github.com/galaxyproject/tools-devteam/blob/d9aeab1fa4810510dcf4ccd41497a10c7e2ede8f/tool_collections/vcflib/vcfleftalign/tool-data/tool_data_table_conf.xml.sample#L5?
(also for vcfgeno2haplo, vcfcheck, vcfvcfintersect, and vcfprimers tools)

The definition for that index file has had 4 columns vs. the 3 defined in those `.sample` files (see https://github.com/galaxyproject/usegalaxy-playbook/blob/master/files/galaxy/usegalaxy.org/config/tool_data_table_conf.xml#L143).

**Comment by nsoranzo** [comment]
It is indeed wrong, it should be the 4-column version, in fact the `fasta_indexes.loc.sample` files in the same directories use the 4 columns in the examples.

**Comment by afgane** [comment]
+1 Thanks.

**Comment by nsoranzo** [comment]
@afgane Do you mean +1 to my comment or to the fix in #168? May I merge it?

**Comment by afgane** [comment]
I was referring to the fix.
