### ISSUE TITLE
Error parsing DT tag picard_MergeSamFiles.xml

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#157]
When using the date tag (DT) in the format specified on the BWA tool form for read group info, this tool produces a successful dataset, but in the comments this appears. Similar to error for Merge BAM Files.

`Picked up _JAVA_OPTIONS: -Xmx2048m -Xms256m Ignoring SAM validation error: WARNING: File /mnt/galaxy/files/000/dataset_216.dat, Error parsing SAM header. DT tag value '$rg.DT' is not parseable as a date. Line: @RG    ID:one  SM:one  PL:ILLUMINA LB:$rg.LB   CN:`

Galaxy Tool Version 1.126.0

**Comment by bgruening** [comment]
This looks like a BWA wrapper bug to me. Somehow the values of `$rg.DT` is not inserted into the field.
You are using the latest version, aren't you?
https://github.com/galaxyproject/tools-devteam/blob/master/tools/bwa/bwa_macros.xml#L9

Also found this change recently: https://github.com/galaxyproject/tools-devteam/commit/8804d5bcebbae4197f39705994069d25b2cd0b79

Can you please confirm which version you are using?

**Comment by jennaj** [comment]
Map with BWA - map short reads (< 100 bp) against reference genome (Galaxy Tool Version 0.2.1)

https://toolshed.g2.bx.psu.edu/view/devteam/bwa/607ca4b95837

**Comment by bgruening** [comment]
@jmchilton fixed it in https://github.com/galaxyproject/tools-devteam/commit/8804d5bcebbae4197f39705994069d25b2cd0b79 but this is not uploaded to the MTS. Can anyone upload this version? This seems to be a serious bug.

@jennaj regarding the error message, I hope https://github.com/galaxyproject/tools-devteam/pull/164 will make it fail.

ping @martenson

**Comment by martenson** [comment]
MTS is updated with latest bwa repo code: https://toolshed.g2.bx.psu.edu/view/devteam/bwa/ac30bfd3e2a8

**Comment by bgruening** [comment]
@martenson thanks!
@jennaj can you test this easily?

**Comment by martenson** [comment]
I installed the new version on https://test.galaxyproject.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/devteam/bwa/bwa/0.2.3 for testing purposes

**Comment by jennaj** [comment]
Passed testing long ago and latest version since then works fine, too. Closing.
