### ISSUE TITLE
Creating a custom build using a .len file triggers an error

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#163]
Description is in this biostars post. Replicated on Main by jen. To replicate as well, just use the example data. Fails for both a browsed/loaded len file or for one that is pasted in.

https://biostar.usegalaxy.org/p/12710/#12740

**Comment by jennaj** [comment]
I cannot add labels .. can someone promote me to that level? Or is that reserved for the new git review group?

**Comment by jmchilton** [comment]
@jennaj You are listed here https://github.com/galaxyproject/galaxy/blob/dev/doc/source/project/organization.rst - so you are in the git review group - so I think you should be in the corresponding group on github. I'll look into that.

**Comment by jennaj** [comment]
Thanks @jmchilton. I don't think I am added to the group Playbook either. @natefoo was going to add my key, but hasn't happened yet - can you help? I am locked out of the bitbucket version, so couldn't add myself there before the move. Might as well sort it all out.

Then we delete these comments here, are unrelated to the issue above!

**Comment by nsoranzo** [comment]
Should it be an issue for https://github.com/galaxyproject/galaxy instead?

**Comment by jmchilton** [comment]
@jennaj - I sent you an invitation to the organization and the required group - it is listed in github as "pending" so I guess it should be in your e-mail somewhere. The same group has access to tools-devteam, galaxy, and the playbook.

**Comment by jennaj** [comment]
@jmchilton thanks, doing
@nsoranzo yes, that sounds good. can this be moved? or delete and create new?

**Comment by nsoranzo** [comment]
@jennaj I don't think it is possible to move an issue to another repository. I'm closing this and you can create the new one.
