### ISSUE TITLE
vcffixup is loaded on usegalaxy.org twice under NGS: VCF Manipulation

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#167]
Galaxy Tool Version 0.0.2
Galaxy Tool Version 0.0.3

Point to different repos/tool owners.

Goals is to not just have one tool on main, but to help users know which to load from the MTS. However best done is OK: 
1) remove the older version if not needed/not current/had an issue
2) only hiding older version in main's tool panel (if needed for backwards compatibility use in existing workflows?)
3) merge repos (if possible, best), replace both in MTS, then loading that repo on main so version menu captures both
4) remove older version from MTS (not best)
5) some other even better alternative

**Comment by nsoranzo** [comment]
The tools are showed separately because they have different ToolShed owner:

toolshed.g2.bx.psu.edu/repos/devteam/vcffixup/vcffixup/0.0.3
toolshed.g2.bx.psu.edu/repos/anton/vcffixup/vcffixup/0.0.2

Best solution is 2).

Probably should be a Trello card instead of an issue here.

**Comment by bgruening** [comment]
I'm with @nsoranzo here.
@nekrut could you deprecate your repository in favour of the devteam one?

**Comment by martenson** [comment]
Deprecating Anton's vcflib and hiding/uninstalling it on Main seems like the best solution to me.

meta: This is not code related issue, I am with @nsoranzo for sticking this into Trello.

**Comment by bgruening** [comment]
@martenson can you take care of this and close this issue please.
I think it can be confusing for users to know where to post such problems so we should take care of this and redirect reports.

**Comment by martenson** [comment]
I marked all the repo's from @nekrut deprecated and I hid all the tools on Main.

**Comment by bgruening** [comment]
Thanks @martenson
