### ISSUE TITLE
tool_dependencies.xml removed from fastx_nucleotides_distribution ToolShed repo

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/tools-devteam#189]
File tool_dependencies.xml in ToolShed repository fastx_nucleotides_distribution has been removed by mistake:

http://toolshed.g2.bx.psu.edu/repos/devteam/fastx_nucleotides_distribution/rev/9353010b95df

from @nsoranzo on [trello](https://trello.com/c/o7EdHIiD/1708-tool-dependencies-xml-removed-from-fastx-nucleotides-distribution-toolshed-repo)

**Comment by bgruening** [comment]
@davebx can we re-upload this repository please?
Thanks! :)

**Comment by erasche** [comment]
ping @davebx

**Comment by bernt-matthias** [comment]
Guess tool_dependencies.xml is deprecated now anyways.
