### ISSUE TITLE
BWA update problem in toolbar

### ISSUE THREAD

**Issue by kaktus42** [galaxyproject/tools-devteam#197]
Installing versions 0.2.2 and 0.3.1 of bwa from devteam from main TS leads to one entry for BWA and two entries for BWA-MAM in the menu

**Comment by bgruening** [comment]
ping @jmchilton. This sounds like an old bug in grouping of tools.

**Comment by nsoranzo** [comment]
This is a Galaxy bug, I've opened https://github.com/galaxyproject/galaxy/issues/552 to track the issue.
