### ISSUE TITLE
eXpress wrapper still depending on old version

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-devteam#215]
The eXpress wrapper is depending on version 1.1.1 but there is already an updated version in the IUC repository (1.5.1), which is already in the MTS.
Is there any reason the wrapper are not updated?

https://toolshed.g2.bx.psu.edu/view/devteam/express/7b0708761d05
https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_express_1_5_1

@davebx seems you have written the latest eXpress package ... any plan? Any non-pushed branches?

**Comment by bernt-matthias** [comment]
Closing because packages are outdated
