### ISSUE TITLE
Cuffdiff produces output with datatype "text" (invalid type) instead of "txt"

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#222]
Version: https://toolshed.g2.bx.psu.edu/view/devteam/cuffdiff/4e6f043995ff

Output files: read group info & run info

This means that the files are not readable when the "eye" in the Galaxy UI is clicked on (a download is prompted instead). Maybe are for downstream use, but use in the UI seems important too - is there a solution?

Pics: 
<img width="245" alt="screen shot 2015-09-15 at 9 21 44 am" src="https://cloud.githubusercontent.com/assets/8999735/9882856/b5c145ac-5b8b-11e5-8098-dab9a7ebd9bb.png">
<img width="245" alt="screen shot 2015-09-15 at 9 22 00 am" src="https://cloud.githubusercontent.com/assets/8999735/9882864/bbefb558-5b8b-11e5-86b7-5f111ea26cee.png">

**Comment by davebx** [comment]
Thank you for reporting this, I've updated the output format in github 
and will be propagating it to the toolshed shortly. Is this the cuffdiff 
installed on the public Galaxy server?

-
Dave Bouvier
http://galaxyproject.org
http://usegalaxy.org

**Comment by davebx** [comment]
@jennaj Additionally, you can set the datatype manually by clicking the pencil icon and going to the datatype tab in the center pane.

**Comment by jennaj** [comment]
Thanks @davebx that was really quick! Yes, this version is on Main so that will need an update.  jen
