### ISSUE TITLE
404 link for rmap source code rmap_v2.05.tbz2

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-devteam#234]
We have cached copies of the rmap 2.05 binaries on depot.galaxyproject.org but not the the source code, `` tools-devteam/packages/package_rmap_2_05/tool_dependencies.xml`` still uses the URL ``http://www.cmb.usc.edu/people/andrewds/rmap/rmap_v2.05.tbz2`` which is 404.

I've not been able to find the source code on the author's newer website, but filed an issue: https://github.com/smithlabcode/rmap/issues/14

Found while testing https://github.com/galaxyproject/planemo/pull/310

**Comment by saketkc** [comment]
Source is here: http://smithlabresearch.org/downloads/rmap_v2.05.tbz2

**Comment by bgruening** [comment]
Thanks @saketkc! I have created a PR!

**Comment by peterjc** [comment]
PR merged, thanks @bgruening - all that remains is one of the devteam updating this on the Tool Sheds...

**Comment by bgruening** [comment]
ping @martenson

**Comment by martenson** [comment]
don

**Comment by peterjc** [comment]
Thanks all :)
