### ISSUE TITLE
picard_CollectAlignmentSummaryMetrics.xml invalid value for MetricAccumulationLevel

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/tools-devteam#244]
When selecting all, the tool erros with this message (picard 1.126):
ERROR: 'ALL_READS,SAMPLE,LIBRARY,READ_GROUP' is not a valid value for MetricAccumulationLevel.

From the help:
METRIC_ACCUMULATION_LEVEL=MetricAccumulationLevel
LEVEL=MetricAccumulationLevel 
The level(s) at which to accumulate metrics.    Possible values: {ALL_READS, SAMPLE, LIBRARY, READ_GROUP} **This option may be specified 0 or more times**. This option can be set to 'null' to clear the default list. 

So I assume the list should be split to create "METRIC_ACCUMULATION_LEVEL=ALLREADS METRIC_ACCUMULATION_LEVEL=SAMPLE" etc.

**Comment by bgruening** [comment]
@scholtalbers can you test this PR?
