### ISSUE TITLE
"Extract MAF blocks" usage: prevent submit without required inputs & update database filter

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#252]
Cannot reference Tool Shed repo - does not seem to be there (?) or I missed it.

*Issue 1* 
The tool will currently allow job submission even when the ref genome is not specified - a required input. This results in a job that runs but always ends in cryptic error.

*Issue 2*
The tool cannot be launched from the history with an input dataset that is queued (grey) or processing (yellow), presumably because the database metadata attribute cannot be accessed for ref genome selection. The database filter is to help the user pick the right one. However, in practical usage this is tedious and maybe not so helpful. We have removed this filter/"database selection helper" function from other tools for similar reasons.

Suggest either removing the filter against database (easy) or inheriting database from the input dataset to the queued/processing job (seems difficult). Like the first. Last has input complexities - for example: could be a string of inputs in queue with no guarantee that the earliest available "done" dataset will have database assigned yet.

**Comment by nsoranzo** [comment]
@jennaj This tool is not on the Tool Shed (yet), it is still in `galaxy/tools/maf/interval2maf.xml` . Please open an issue on https://github.com/galaxyproject/galaxy/ .

Moreover, Issue 1 seems more a Galaxy-related problem than tool-related, and I cannot replicate it on the Galaxy `dev` branch.

**Comment by jennaj** [comment]
I described this poorly. The genome is extracted from the MAF contents itself, not a ref genome in the sense of an indexed reference genome (dbkey) on the server. 

So #1, still an issue. And #2 I think is a non-solvable issue - the dataset must be available to the tool before it can be launched (when executed from the history) unless we permit simple entry without verifying it against the input first - and that is likely desirable behavior to avoid a casecase of other issues. I'll close this out and open it correctly under /galaxy. And make another ticket to get this added to the tool shed.

**Comment by martenson** [comment]
@jennaj this does not need to be added to the Tool Shed, it is an implicit part of every Galaxy 
we also already have https://github.com/galaxyproject/galaxy/issues/636

**Comment by jennaj** [comment]
Ok, won't add that ticket then. Just made one for usage: https://github.com/galaxyproject/galaxy/issues/984

Thanks @martenson !
