### ISSUE TITLE
mpileup 2.1 failing

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-devteam#255]
lately changed here: https://github.com/galaxyproject/tools-devteam/pull/220

via @jennaj 
Ok, test just finished and failed. 2.1 has a new error. Sent it in as a bug report for full details.

Fatal error: Exit code 139 (Error)
[main] unrecognized command '--version'

**Comment by blankenberg** [comment]
Tool is most likely getting the wrong version of samtools (e.g 0.1.18) as dependency when run.

**Comment by jennaj** [comment]
macs 2.1.1 is on main and executes correctly

**Comment by blankenberg** [comment]
@jennaj the title here mentions mpileup, not macs 2.

**Comment by martenson** [comment]
reopenning to make sure this is tracked properly

**Comment by jennaj** [comment]
sorry, mpileup.

However, that was yesterday early in the day. An odd result came in today and I am retesting that (the user sent a history link in about an hour ago, jobs are running). 

We can close this one out, but re-open another for the new error if reproducible.

**Comment by bernt-matthias** [comment]
Tool has been moved to IUC. Reopen there if the problem is still relevant.
