### ISSUE TITLE
Re-run behavior when multiple tool versions exist is problematic

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#256]
Observed on http://usegalaxy.org with Mpileup v 2.0 and 2.1 (both exist on the server)
1. Re-run of 2.0 is not prompting users about the upgraded version. Older tools versions normally do this.
2. Re-run is not populating the 2.1 form with the 2.0 prior settings when swapping versions. Most tools do this for options that are the same between versions.

Some related tickets:
https://github.com/galaxyproject/tools-devteam/issues/219
https://github.com/galaxyproject/tools-devteam/issues/220
https://github.com/galaxyproject/tools-devteam/issues/255

**Comment by bgruening** [comment]
@guerler is this something for you? :)

**Comment by bernt-matthias** [comment]
Is this still an issue?

**Comment by mvdbeek** [comment]
Very unlikely, and if so it would be a Galaxy issue
