### ISSUE TITLE
possible bug in the kraken data manager

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-devteam#264]
reported by @tiagoantao

I think that there is a bug in the kraken data manager
Try the following
admin>local data>Run data manager tools>Kraken

Select partial library to download> Human

Depending on my galaxy installation I am getting different errors. The most common is not being able to download human chromosomes. But works well with the other options

**Comment by tiagoantao** [comment]
Sorry for not having time to have a look at this. Take the next suggestion
with a grain of salt:
it might be a problem with recent versions of wget which might have a
different behaviour dealing with listing files. I am currently using the
version of the most recent ubuntu.

If you try to replicate this and fail, write here and I will try to find
the time...

On 30 October 2015 at 12:01, Martin Cech <notifications@github.com> wrote:

> reported by @tiagoantao <https://github.com/tiagoantao>
>
> I think that there is a
> Try the following
> admin>local data>Run data manager tools>Kraken
>
> Select partial library to download> Human
>
> Depending on my galaxy installation I am getting different errors. The
> most common is not being able to download human chromosomes. But works well
> with the other options
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/tools-devteam/issues/264>.
>



-- 
"Democracy matters more than any currency arrangement." - Paul Krugman

**Comment by jennaj** [comment]
The most current Kraken DM is now from the IUC repo and is dated 4/2017 in the Tool Shed. 
https://github.com/galaxyproject/tools-iuc/commits/master/data_managers/data_manager_build_kraken_database

I am going to close this out. We can reopen the issue if there are future problems.
