### ISSUE TITLE
BLAST+ fails because of automatical added export rule to env.sh

### ISSUE THREAD

**Issue by yhoogstrate** [galaxyproject/tools-devteam#272]
BLAST+ crashes with:
```
BLAST+_ROOT_DIR=/usr/local/galaxy/blast+/2.2.31/iuc/package_blast_plus_2_2_31/4df9cdbc6e61: not found
/usr/local/src/galaxy/database/job_working_directory/000/230/galaxy_230.sh: 3: export: BLAST+_ROOT_DIR: bad variable name
```
The reason is because BLAST+_ROOT_DIR is automatically generated, I suspect because of:
https://github.com/galaxyproject/galaxy/commit/a6efdc5a2b41979ae824611abdb17a633ed32aaf

**Comment by peterjc** [comment]
The package itself sets ``$BLAST_ROOT_DIR`` explicitly at @bgruening's suggestion: https://github.com/peterjc/galaxy_blast/blob/master/packages/package_blast_plus_2_2_31/tool_dependencies.xml

It looks like in addition to avoiding ``-`` in the auto-generated environment variable name, other characters like ``+`` should be removed? Special characters in package names may be something to consider for the IUC best practises and ``planemo lint``?
