### ISSUE TITLE
Summary statistics fails on usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#277]
Tool: 
tool_collections/galaxy_sequence_utils/fastq_stats/fastq_stats.xml
https://toolshed.g2.bx.psu.edu/view/devteam/fastq_stats/9b7b4e0ca9db

Reported in Trello 9/21/2015: https://trello.com/c/cmqLGxhx

Example input, tabular:
```
1	2
3	4
5	6
7	8
9	10
```

Example error:
```
Traceback (most recent call last):
  File "/galaxy-repl/instances/main/server/tools/stats/gsummary.py", line 119, in <module>
    if __name__ == "__main__": main()
  File "/galaxy-repl/instances/main/server/tools/stats/gsummary.py", line 113, in main
    outfile.write( "%s\n" % "\t".join( [ "%g" % k for k in summary ] ) )
TypeError: float argument required, not str
```

**Comment by nsoranzo** [comment]
Hi @jennaj,
this tool is not on the Tool Shed yet, it's still in https://github.com/galaxyproject/galaxy/tree/dev/tools/stats . Please open an issue on https://github.com/galaxyproject/galaxy/issues/new .

**Comment by bgruening** [comment]
@jennaj this was fixed in 15.07 https://github.com/galaxyproject/galaxy/pull/885
@jmchilton makes sure this will get into to 15.10 and dev

Thanks for reporting!

**Comment by jennaj** [comment]
Great, as it moves through we should use the checklist we were developing. My original that you converted on another ticket with checkboxes is about 90% enough. 

I created an issue to develop a templated checklist for issue resolution that has user eyes on it. Meaning, attach it to any tool or important UI change that goes through this process.

See here:

**Comment by jennaj** [comment]
Note fully resolved yet. See: https://github.com/galaxyproject/galaxy/pull/885
