### ISSUE TITLE
scatterplot crashes

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-devteam#282]
python /usr/local/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/scatterplot/c12b0759203b/scatterplot/scatterplot.py /data/2/galaxy_db/files/000/317/dataset_317644.dat /data/3/galaxy_db/files/000/317/dataset_317646.dat 2 1 "Scatterplot" "V1" "V2"

job stderr:
global name 'array' is not defined

**Comment by nsoranzo** [comment]
`array` should be imported by `from rpy import *`, if numpy is installed when rpy is compiled. We should probably add a requirement on numpy and use an explicit `from numpy import array` .
