### ISSUE TITLE
Install errors reported for package_zlib_1_2_8 , package_samtools_1_1 , cutadapt 1.6 , package_python_2_7_10

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#283]
See Biostar posts: 
- https://biostar.usegalaxy.org/p/14988/
- https://biostar.usegalaxy.org/p/14989/

Posts also reported problems with Galaxy Utils, but once the package was corrected (11/13/15) it installed correctly for at least two users, see this post: https://biostar.usegalaxy.org/p/14631/#15000

**Comment by azyrth** [comment]
The install errors concerning python packages are related to easy_install. Following the instructions of Devon Ryan (https://biostar.usegalaxy.org/p/14989/#15142) solves it.

**Comment by bgruening** [comment]
Is this one still valid? I never have seen this before.

**Comment by jennaj** [comment]
Unknown by me. Others?

**Comment by datakid** [comment]
I'm seeing it at the moment from an 18.05 installation. Not 100% sure how to solve. we run on CentOS 7.5, so at an OS level, zlib 1.2.7 is the best we can do. I'll try reinstalling the dependencies. In the meantime, is there either any way to update the database or documentation on how to safely remove and (try to) reinstall?

**Comment by bgruening** [comment]
We have migrated all our tools to conda packages. @datakid which tool is still using the `packages_*`? We should update this tool to use conda instead.
