### ISSUE TITLE
Samtools rmdup should use v. < 1.0.0

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/tools-devteam#284]
xref.: https://trello.com/c/cmvVu5EF/2742-error-rmdup-is-problematic-on-http-usegalaxy-org

Seen also on TGAC Galaxy server.

Caused by https://github.com/samtools/samtools/issues/393 .

**Comment by jmarshall** [comment]
Note that this has since been fixed (see PR samtools/samtools#461); an `rmdup` command that works as well as it ever did will reappear in the upcoming 1.3 release.

**Comment by afgane** [comment]
I don't guess this fix is in the the ToolShed yet?

I'm still getting 
```
Fatal error: Exit code 134 (Error)
Samtools-htslib-API: bam_get_library() not yet implemented
Aborted (core dumped)
```
from https://toolshed.g2.bx.psu.edu/view/devteam/samtools_rmdup/3735f950b2f5 (i.e.,  *Revision: 2:3735f950b2f5*)

**Comment by bgruening** [comment]
ping @martenson

**Comment by martenson** [comment]
@afgane it is now as of https://toolshed.g2.bx.psu.edu/view/devteam/samtools_rmdup/bb40e4252392
@bgruening thanks for the ping

**Comment by afgane** [comment]
Working now. Thanks.
