### ISSUE TITLE
Install recipe for package_bwa_0_7_10_039ea20639 does not support OS X

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/tools-devteam#295]
This recipe https://github.com/galaxyproject/tools-devteam/blob/master/packages/package_bwa_0_7_10_039ea20639/tool_dependencies.xml only works on Linux platforms while OS X should be supported as well - especially since the Galaxy bwa wrappers here https://github.com/galaxyproject/tools-devteam/tree/master/tools/bwa use it.

**Comment by bernt-matthias** [comment]
Closing this  since packages are outdated.
