### ISSUE TITLE
cairo/pixman and older r releases

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-devteam#298]
There are apparently some issues with the devteam version of pixman,
which are being used by older versions of R.
Should we migrate the recent iuc changes back to devteam?
Also, should we change the owner to iuc in the older R packages?

See http://dev.list.galaxyproject.org/gcc-error-during-pixman-0-32-4-installation-on-Mac-OS-X-10-11-td4668455.html and http://dev.list.galaxyproject.org/Picard-installation-dependency-issues-td4668449.html

**Comment by bgruening** [comment]
+1 for migrating changes back to devteam but leaving the old R packages as they are.

**Comment by mvdbeek** [comment]
Okay, I will do this then.

**Comment by martenson** [comment]
fixed by https://github.com/galaxyproject/tools-devteam/pull/299
thanks @mvdbeek !
