### ISSUE TITLE
weblogo3 tool reports wrong number of sequences to stdout

### ISSUE THREAD

**Issue by bcclaywell** [galaxyproject/tools-devteam#302]
One of our users reported the following today:

> Clicking on the output from that tool (on the right edge of the screen) reveals information about the search.
>
> Eg:  # weblogo input /mnt/silver/galaxy/containers/galaxy-qa/stable/database/files/013/dataset_13858.dat has 2845133 sequences all of length 10

> I noted, in my Excel manipulations that the reported number of sequences (as above) is always 1 smaller than the sum of the 4 nucleotides reported (for each sequence position) by the Sequence
Logo Tool.

It looks like an off-by-one error in [this line](https://github.com/galaxyproject/tools-devteam/blob/8bac50ca5572ea388181835e417b2db09fa27c1a/tools/weblogo3/rgWebLogo3.py#L108) of `rgWebLogo3.py`. `lasti` should be `lasti + 1` since the index is zero-based.

**Comment by bgruening** [comment]
Thanks @bcclaywell!
