### ISSUE TITLE
Wrap a tool that will concatenate all fasta records contained in a single dataset

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#305]
Goal: Concatenate all FASTA records contained within the same dataset into a single fasta sequence

Suggested 3rd party tool: http://www.bioinformatics.org/sms2/combine_fasta.html

Note: There is a tool in the MTS that will split a multi-sequence FASTA dataset into individual FASTA datasets and place them into a dataset collection (Not on Main: https://toolshed.g2.bx.psu.edu/view/rnateam/splitfasta/ae4d5733272f). BUT there is no tool that will take in a dataset collection containing individual FASTA datasets and concatenate all.

**Comment by jmchilton** [comment]
I developed a tool for Galaxy-P that would be compatible with collections that did this I think - https://toolshed.g2.bx.psu.edu/repository?repository_id=1648599b6784efd6&changeset_revision=2904d46167da.

**Comment by jennaj** [comment]
@jmchilton I think this is a good solution - I missed it in my tool shed search - sorry!

I wonder if we could get both of these tools onto Main as a pair (with the help referencing the other to aid users with usage): splitfasta + fasta_merge_files_and_filter_unique_sequences)

What do you think?

**Comment by bgruening** [comment]
@jennaj you can do this with removing the header and all empty lines + an optional fasta reformatting, isn't it? Alternatively, you can use FASTA to tabular and just take the second column.

Unique sequences you can also easily get with FASTA-to-tabular and using uniq on the second column.
Is a new tools really needed for this?

Regarding `splitfasta` we wrote this tool to workaround a limitation in the framework. Personally, I would like to see the build in `parallelism` mode gets fixed to this splitting can be done on a framework level and we don't need a user to manually do it. VCF tools can also profit from it: https://github.com/galaxyproject/tools-devteam/pull/265

@jennaj can you please post these things to tools-iuc? I think devteam is only in maintenance mode and we will not add new tools to it. You will also get more viewers if you post it there :)

**Comment by jennaj** [comment]
@bgruening That is a great solution - didn't think of it! But now seems like a "duh!" :)

And will start posting tool requests to IUC - thanks!

I think we can close this out. The user who wanted to perform the operation was given this ticket to track.

**Comment by bgruening** [comment]
Glad it was useful!

**Comment by erasche** [comment]
While I appreciate @bgruening's love of the small unix tools + workflows for solving Galaxy tool needs, I'd really love to have this as a proper tool. We have one we use here that I'm happy to upstream if y'all want, but I imagine @jmchiton's galaxyp tool does it just as well. 

4 steps (with one being a workflow incompatible upload step) isn't really a workable solution in many cases, goodness knows my users would rather copy and paste manually even if it takes twice as long, rather than learning three new tools, or using a workflow.

**Comment by bgruening** [comment]
How you create your own header is up to the user and does not count as incompatible step ;)
I think my point here and with other tools is, people need to learn this lego-magic. We can not provide for every possible problem a tools, at least I don't want to maintain them. If we can convince our users to learn these 3 powerful tools, they learn more than the sum of its parts. In the end they can solve more problems on there own. With this logic a new tool that is just for one specific problem is a tool that is useless to learn for most of the problems, whereas the other 3 tools are worth to learn for more than one problem.

Not sure if I made my point clear enough :(

**Comment by blankenberg** [comment]
+1 for Lego bits. Master using sweet-sweet (linux, tabular, etc) tools, and you have something that applies even to the next project. 

Of course, some standard formats do deserve a bit more custom tool love. ;)

**Comment by erasche** [comment]
@bgruening perhaps so. I would *love* it if everyone learnt to use the small re-usable tools

> If we can convince our users to learn these 3 powerful tools, they learn more than the sum of its parts. In the end they can solve more problems on there own.

your point was well made, and I'm completely behind it. However for small tasks... I'm willing to write and maintain tools to solve problems like these.

My rationale for writing a tool for this specific use case (I encountered it locally):

- 5 minutes
- can use in workflows
- zero training required
- search tool menu for "concat" and it shows up.

versus actually training users on this:

- hours? days?
- can be used easily in workflows (subworkflows will help mitigate this problem)
- every user creates their own version (no standardisation; workflows-as-tools which can be installed in their toolbox would solve this)

I'm 100% with you, I would really, *really*, **really** love everyone to understand and use the unix approach to tools but that logic is a stretch for some of them, and the amount of training is really hard to accomplish for me.

**Comment by erasche** [comment]
Then again, my user demographic is people who are unable to use the linux command line and these concepts are harder to grasp for them, they're terrified and turned off by the lack of a tool (or tool-like workflow) that already exists to solve their problems.

**Comment by jennaj** [comment]
Both solutions makes sense to me, so you all pick the best path. 

I think teaching users how to "lego" functions that those used to the command-line recorgnize, but that are somewhat foreign to others, can be really empowering. It is becoming clear that any biologist working with larger data is going to need some literacy (if not actual implimentation skills) in this area to be successful & independent.

That said, simple tools that do simple tasks are very convinient :)

PS: Stating the obvious, but just in case (maybe for users following the ticket): I added the step for "Upload > Paste header" in the solution to simplify the steps and allow some customization. On way to workflow it is to slice off the first sequence identifier and concatinate it back on at the very top in the final step.
