### ISSUE TITLE
Where is Samtools index? 

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/tools-devteam#343]
I installed the samtools 1.2 suite on my galaxy, but one of the functions I use in my local script, samtools index, isn't in the suite. [Samtools docs here](http://www.htslib.org/doc/samtools.html). Am I just missing it, or is it not included in the suite?

**Comment by peterjc** [comment]
Galaxy likes to keep all BAM files as sorted BAM, so there is no need to explicitly call ``samtools index``.

**Comment by zfrenchee** [comment]
To visualize the bam file later in tools like IGV the software typically requests a .bai file. Is there a workaround?

**Comment by peterjc** [comment]
Does this work for you?

1. Open Galaxy
2. Click on BAM file in history
3. Click on disk icon (Download)
4. Mini menu appears with download links for the BAM and the BAI file

**Comment by zfrenchee** [comment]
Thanks!

**Comment by peterjc** [comment]
Yay. Solved.

**Comment by bgruening** [comment]
@zfrenchee also please note that Galaxy can directly stream you BAM file to your IGV instance. There is no need to download BAM file to visualize them.

**Comment by peterjc** [comment]
So just copy and paste the URL for the BAM file into IGV (or many other BAM viewers able to take a remote file)?

**Comment by bgruening** [comment]
@peterjc You can enable this in Galaxy natively. There will be a link on you BAM datasets called: `display in IGV local`
