### ISSUE TITLE
Where is Samtools view? 

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/tools-devteam#346]
Hello, 
Another naive question, but I'm trying to filter out mitochondrial reads from a bam file on galaxy. Right now I'm essentially mimicking [this approach](https://www.biostars.org/p/128967/) with 

`samtools idxstats input.bam | cut -f 1 | grep -v MT | xargs samtools view -b input.bam > output.bam`

except the last step requires `samtools view -b`. I'm thinking there's either a blindingly obvious way to do this or there's just a better way to filter out mitochondrial reads on galaxy. Hints in either of those directions would be super helpful!

**Comment by zfrenchee** [comment]
See #347

**Comment by zfrenchee** [comment]
This would actually be a really useful tool for another reason:
When I ran Bamtools filter, I got this error:

```
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_index_core] truncated file? Continue anyway. (-4)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
Aborted (core dumped)
[W:
```

Which [this thread](http://seqanswers.com/forums/showthread.php?t=19228) claims could be solved with samtools view Bam -> Bam.

**Comment by bgruening** [comment]
Hi!

If I understand it correctly you want to filter you BAM file by reads that are mapping to the mitochondrial genome, is this correct?

If so you can use this tool: `Filter SAM or BAM, output SAM or BAM files on FLAG MAPQ RG LN or by region`. It uses samtools filter and you can simply filer your regions by providing a region file (BED).

A second more hacky way would be to convert your BAM to SAM, filter for your MT characters and convert it back to BAM.

The above error looks like your input file is broken.

I guess these kind of questions are better suited for https://biostar.usegalaxy.org/.

Hope this helps,
Bjoern

**Comment by zfrenchee** [comment]
Hi Bjoern, 
That tool might do the trick, though I'm trying to get _rid_ of chrM, and filtering it out seems non-obvious with this tool, which seems to be built to pick reads out of a file, not throw reads away. 

Alright, I'll use the forum next time.
