### ISSUE TITLE
Job submission failed:  Tool not found or not accessible.

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/tools-devteam#347]
I've just installed [Bamtools filter](https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/bamtools/bamtools_filter), and although the tool looks like exactly what I need, when I go to run it, I encounter that error. Any ideas?

**Comment by zfrenchee** [comment]
I waited a little bit and then ran it again. This time I got:

`This tool was disabled before the job completed.  Please contact your Galaxy administrator.`

Why is this happening?

**Comment by nsoranzo** [comment]
Try to restart the Galaxy server after installing each tool. Unfortunately this can happen if you have configured Galaxy to run with more than one webserver.

**Comment by zfrenchee** [comment]
Worked.
