### ISSUE TITLE
SamMerge incorrectly sets history item in error state

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-devteam#358]
If validation stringency is set to lenient, picard's sam merge will output lines like:

```
Ignoring SAM validation error: ERROR: Record 756642, Read name JLK5VL1:491:H7MJPADXX:2:1208:10042:53852, MAPQ should be 0 for unmapped read.
```

Galaxy matches this and outputs:

```
Fatal error: Matched on error:
```

toolshed.g2.bx.psu.edu/repos/devteam/sam_merge/sam_merge2/1.2.0

**Comment by nsoranzo** [comment]
I think this tool should be deprecated in favour of "MergeSamFiles merges multiple SAM/BAM datasets into one" from https://toolshed.g2.bx.psu.edu/view/devteam/picard/ .

**Comment by bernt-matthias** [comment]
Closing via https://github.com/galaxyproject/tools-devteam/pull/572
