### ISSUE TITLE
Tophat has a mismatch between default params and command-line triggering failures

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#365]
**Issue**

This option Coverage Search (under full params) is marked as "No" by default, yet is not included in the command-line. This causes certain jobs to fail (likely for resource) but the error output is not captured as exceeding memory or wall-time. **UPDATE: THIS IS A GUESS, NOT CONFIRMED. The root cause of the problem is still an unknown.**

**UI setting**

<img width="700" alt="tophat_default_coverage_search" src="https://cloud.githubusercontent.com/assets/8999735/14537112/787bd91e-022a-11e6-89b4-b213ec3a5023.png">

**Command-line**

Note that it is missing
> --no-coverage-search

Command-line from job info page in UI

> Job Command-Line:	tophat2 --num-threads ${GALAXY_SLOTS:-4} -r 250 --mate-std-dev=20 --no-discordant /galaxy/data/mm10/bowtie2_index/mm10 "/galaxy-repl/main/files/014/976/dataset_14976631.dat" "/galaxy-repl/main/files/014/976/dataset_14976632.dat"

**Example Error**

Error for this type of job is always a trace dump and ending at the same point .. where junctions are written. I assume because there are way too many. Not all jobs fail for this .. tends to be linked with certain data combinations (fragmented genomes and/or high coverage/targetted region fastq seq reads = both tend to produce more discovered "junctions")

> job stderr:
> Fatal error: Tool execution failed
> 
> [2016-03-28 07:07:14] Beginning TopHat run (v2.0.14)
> -----------------------------------------------
> [2016-03-28 07:07:14] Checking for Bowtie
>                   Bowtie version:        2.2.5.0
> [2016-03-28 07:07:15] Checking for Bowtie index files (genome)..
> [2016-03-28 07:07:15] Checking for reference FASTA file
> [2016-03-28 07:07:15] Generating SAM header for /galaxy/data/mm10/bowtie2_index/mm10
> [2016-03-28 07:07:21] Preparing reads
>          left reads: min. length=75, max. length=75, 177927354 kept reads (23727 discarded)
>         right reads: min. length=75, max. length=75, 175340316 kept reads (2610765 discarded)
> [2016-03-28 08:40:24] Mapping left_kept_reads to genome mm10 with Bowtie2
> [2016-03-28 11:16:27] Mapping left_kept_reads_seg1 to genome mm10 with Bowtie2 (1/3)
> [2016-03-28 11:31:30] Mapping left_kept_reads_seg2 to genome mm10 with Bowtie2 (2/3)
> [2016-03-28 11:48:29] Mapping left_kept_reads_seg3 to genome mm10 with Bowtie2 (3/3)
> [2016-03-28 12:05:28] Mapping right_kept_reads to genome mm10 with Bowtie2
> [2016-03-28 14:28:38] Mapping right_kept_reads_seg1 to genome mm10 with Bowtie2 (1/3)
> [2016-03-28 14:44:18] Mapping right_kept_reads_seg2 to genome mm10 with Bowtie2 (2/3)
> [2016-03-28 15:00:01] Mapping right_kept_reads_seg3 to genome mm10 with Bowtie2 (3/3)
> [2016-03-28 15:15:43] Searching for junctions via segment mapping
> [2016-03-28 15:49:24] Retrieving sequences for splices
> [2016-03-28 15:51:24] Indexing splices
> Building a SMALL index
> [2016-03-28 15:52:26] Mapping left_kept_reads_seg1 to genome segment_juncs with Bowtie2 (1/3)
> [2016-03-28 16:02:59] Mapping left_kept_reads_seg2 to genome segment_juncs with Bowtie2 (2/3)
> [2016-03-28 16:14:37] Mapping left_kept_reads_seg3 to genome segment_juncs with Bowtie2 (3/3)
> [2016-03-28 16:24:57] Joining segment hits
> [2016-03-28 16:45:10] Mapping right_kept_reads_seg1 to genome segment_juncs with Bowtie2 (1/3)
> [2016-03-28 16:54:51] Mapping right_kept_reads_seg2 to genome segment_juncs with Bowtie2 (2/3)
> [2016-03-28 17:06:59] Mapping right_kept_reads_seg3 to genome segment_juncs with Bowtie2 (3/3)
> [2016-03-28 17:17:35] Joining segment hits
> [2016-03-28 17:35:26] Reporting output tracks
>         [FAILED]
> Error running /galaxy-repl/main/deps/tophat/2.0.14/iuc/package_tophat_2_0_14/536f7bb5616d/bin/tophat_reports --min-anchor 8 --splice-mismatches 0 --min-report-intron 50 --max-report-intron 500000 --min-isoform-fraction 0.15 --output-dir ./tophat_out/ --max-multihits 20 --max-seg-multihits 40 --segment-length 25 --segment-mismatches 2 --min-closure-exon 100 --min-closure-intron 50 --max-closure-intron 5000 --min-coverage-intron 50 --max-coverage-intron 20000 --min-segment-intron 50 --max-segment-intron 500000 --read-mismatches 2 --read-gap-length 2 --read-edit-dist 2 --read-realign-edit-dist 3 --max-insertion-length 3 --max-deletion-length 3 -z gzip -p6 --inner-dist-mean 250 --inner-dist-std-dev 20 --no-closure-search --no-coverage-search --no-microexon-search --sam-header ./tophat_out/tmp/mm10_genome.bwt.samheader.sam --report-mixed-alignments --samtools=/galaxy-repl/main/deps/tophat/2.0.14/iuc/package_tophat_2_0_14/536f7bb5616d/bin/samtools_0.1.18 --bowtie2-max-penalty 6 --b
>  owtie2-min-penalty 2 --bowtie2-penalty-for-N 1 --bowtie2-read-gap-open 5 --bowtie2-read-gap-cont 3 --bowtie2-ref-gap-open 5 --bowtie2-ref-gap-cont 3 /galaxy/data/mm10/bowtie2_index/mm10.fa ./tophat_out/junctions.bed ./tophat_out/insertions.bed ./tophat_out/deletions.bed ./tophat_out/fusions.out ./tophat_out/tmp/accepted_hits ./tophat_out/tmp/left_kept_reads.mapped.bam,./tophat_out/tmp/left_kept_reads.candidates ./tophat_out/tmp/left_kept_reads.bam ./tophat_out/tmp/right_kept_reads.mapped.bam,./tophat_out/tmp/right_kept_reads.candidates ./tophat_out/tmp/right_kept_reads.bam
> Loaded 351284 junctions
> 

**Scope creep**

Could we modify the tool to report the command-line in bug reports when making this change? Would be super helpful. Currently, all that comes out is:

> job command line:
> None

**Example shared history**

https://usegalaxy.org/u/jen/h/tophat-coverage-search-option-issue

**Comment by nsoranzo** [comment]
@jennaj You are using the pre-set ("Use Defaults") options here, right?
In this case neither `--coverage-search` nor `--no-coverage-search` option is used. According to the [TopHat manual](https://ccb.jhu.edu/software/tophat/manual.shtml), coverage search is disabled by default for reads 75bp or longer.

**Comment by jennaj** [comment]
@nsoranzo This is true, but a small percentage of jobs seem to be failing because coverage search being used. Would it make sense to add this to the command-line for all jobs run with default settings, since the tool form states that it is set to "no" (for all read lengths)? 

The problem is that there is currently no way to override and set "no" for sequences under 75 bps.

**Comment by nsoranzo** [comment]
@jennaj I think that "Use Defaults" has to be interpreted as "leave TopHat decide what options are best", so I don't think that adding `--no-coverage-search` option to the command is appropriate in this case. Instead, when using "Full parameter list", we should probably add a value "Auto" to the "Use Coverage Search" select, which should be the default, explaining in the help that this depends on the read lenghts.

By reading your log, I see that `tophat_reports` is invoked with the option `--no-coverage-search`, so maybe this is not the cause of the job failure?

**Comment by jennaj** [comment]
Thanks @nsoranzo 

The truth is that I do not know the root cause of the issue, only that this comes up sometimes and all inputs are find. This small difference seems like a good candidate to start a discussion to find out why because of where the job ends and the way the parameter was modeled. 

Even if not related, I like the idea of using "Auto" at default, since that would allow a yes/not selection by a user invoking advanced options to truly pick whether to use the option or not. 

I couldn't find anything relevant in the Tophat release notes (current fixes, etc). https://ccb.jhu.edu/software/tophat/index.shtml

**Comment by jennaj** [comment]
Let's leave this open until pull-request accepted and updated tool is on Main and tested there. Idea is to help users on that server, following the change, to know when to use the tool again there.

**Comment by jennaj** [comment]
@nsoranzo @bgruening Will the update include upgrading Tophat? I read through the linked tickets but cannot tell. However, using Tophat 2.1.1 is reported to solve the original root problem this ticket was based on (but param modeling is also good!). See some public user comments here: https://biostar.usegalaxy.org/p/17521

**Comment by nsoranzo** [comment]
@jennaj The updated wrapper depends now on TopHat 2.1.0, but has not reached Galaxy Main yet.

**Comment by jennaj** [comment]
Ok, thanks @nsoranzo 

I'll test this usage out with the 2.1.0 wrapped version and see if resolved, once updated on main. I saw that @bgruening pinged @davebx about it already in another ticket and am following. Will close this one out when testing passes.

**Comment by jennaj** [comment]
Temporary work-around: jobs that encounter this error can be executed with HISAT2 as an alternative mapper.

**Comment by jennaj** [comment]
@nekrut @martenson @davebx 

Request to update Tophat at http://usegalaxy.org to wrapper v 2.1.0.

**Comment by martenson** [comment]
@jennaj Nate is going through the playbooks to make them update Galaxy tools properly with our new deployment file system. Until then we need to either wait or if it is important urge him to do some tools manually (but that slows down the process of updating the playbooks)

**Comment by jennaj** [comment]
@martenson @natefoo 

It seems important since this is one of the most used tools on main, it addresses a specific failure case that is based on the binary itself, and it has been a problem for a while now. If we could update, would be great for our users.

**Comment by jennaj** [comment]
FYI - retesting Tophat for all known prior failure types - updated when complete

**Comment by natefoo** [comment]
I'll update, sorry I missed the previous ping.

**Comment by jennaj** [comment]
@natefoo I noticed that the wrapper is at v 2.1.0 on Main last night (but without the "updated" tool panel tag), so thought it was ready to test. I did find the new options for coverage. So guessing that Main does not need more adjustments unless you wish to add the "updated" UI tag.

 - The accepted hits dataset output metadata problem remains (but just that single dataset, rest are OK). Not part of this ticket specifically, but seemed worth checking out with new tool version.
 - Runs with the new coverage option (testing all three, using the same test history as in original ticket above) are still executing - this is good news as the prior runs failed after this much time. More feedback once they finish.

**Comment by natefoo** [comment]
Yeah, I just went to update it and discovered that it's already the newest version. Apparently the latest version has been installed since 6/22.

**Comment by jennaj** [comment]
@natefoo Runs with the new coverage option auto (default) and a hard no were successful. The run with a hard no is still running but expected to fail (walltime). Let's consider this done and closed :) Thanks!

**Comment by martenson** [comment]
@natefoo @jennaj sorry for not updating the post(s), I did major tool updates once I have learned the new setup in June

**Comment by jennaj** [comment]
@martenson All good. If you recall those that were updated, could you send me a list of the updated tools (direct, not here)? Easier than hunt-n-peak or going through just those with known issues.

**Comment by martenson** [comment]
@jennaj that recall is something I am unable to do, however all that were reported buggy and had updates in June, were updated

**Comment by jennaj** [comment]
@martenson Ok, I am working through my list of known issues again and retesting. That should be enough to start with. Thanks!!

**Comment by martenson** [comment]
@jennaj For quite some time the changes in tools on Main are tracked via usegalaxy-playbook (all commits here: https://github.com/galaxyproject/usegalaxy-playbook/commits/master) - usually the commits like this: https://github.com/galaxyproject/usegalaxy-playbook/commit/8a200a9e655c5814b0a0bee8b919aca16315e5fc are the ones that follow tool updates (update mutable configs is common commit message)

**Comment by jennaj** [comment]
@martenson Perfect, thanks, wasn't sure exactly if had/where to look :)
