### ISSUE TITLE
Picard ValidateSamFile errors (as a green successful dataset) in summary mode

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#369]
**Version**

toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_ValidateSamFile/1.136.0

**Issue**

Summary mode produces error "green successful" dataset. Likely because max line limit is a required value when should only apply to verbose mode. Not sure why error reporting the param is interpreted as a "type" (?)

> Warning: Exit code 1 () Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/scratch ERROR: 'MAX_OUTPUT=100' is not a valid value for Type.

<img width="240" alt="screen shot 2016-04-26 at 10 44 22 am" src="https://cloud.githubusercontent.com/assets/8999735/14828460/ec443f74-0b9b-11e6-8692-370846de84cd.png">

<img width="633" alt="screen shot 2016-04-26 at 10 35 10 am" src="https://cloud.githubusercontent.com/assets/8999735/14828409/bdcd6206-0b9b-11e6-945c-7fa4fd155467.png">

<img width="628" alt="screen shot 2016-04-26 at 10 34 37 am" src="https://cloud.githubusercontent.com/assets/8999735/14828413/c1591154-0b9b-11e6-8211-998b832ff118.png">

**Impacts**

Anyone that installs tool plus Galaxy Main http://usegalaxy.org

**Reported at**

https://biostar.usegalaxy.org/p/17241/

**Comment by nsoranzo** [comment]
I think this is caused by Galaxy Main not being updated to latest 16.04 commit, see https://github.com/galaxyproject/galaxy/issues/2245#issuecomment-214458058 .

**Comment by martenson** [comment]
the fix is now on Main, please retest @jennaj

**Comment by jennaj** [comment]
Works on main now. Thanks!

ps: The tool does not function on Tophat output - not sure if all RNA alignments are not. Running a few tests. We should specify that in the help (or in support wiki) if is the case.
