### ISSUE TITLE
Parallelize freebayes

### ISSUE THREAD

**Issue by jgoecks** [galaxyproject/tools-devteam#370]
Freebayes can parallelize execution across genome regions: https://github.com/ekg/freebayes/blob/master/scripts/freebayes-parallel

This should definitely be done to reduce runtime; an exome can be analyzed in ~20 minutes using 8 cores. Here's an outline for how to do it:
- add dependencies on vcflib and gnu parallel
- add loc file for fa.fai indices
- update freebayes bundle on depot to include necessary scripts: freebayes-parallel, fasta_generate_regions.py, and vcffirstheader (if not in vcflib)
- update wrapper to use freebayes-parallel and do not use --vcf option, which does not work in parallelized mode

Parallelized execution can be slow when calling variants for a small number of regions, so it may be necessary to have an option to turn off parallelization.

**Comment by bgruening** [comment]
Please comment/review on this PR: https://github.com/galaxyproject/tools-devteam/pull/265

**Comment by bgruening** [comment]
ping @jgoecks

**Comment by bgruening** [comment]
We have some support for it now.
