### ISSUE TITLE
BAMTools Convert, Merge, Randomize - Fails for Convert to Bed + Yaml

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#378]
Other options successful with coordinate sorted input (but not all functions require it).

Two error types, depending on the "convert to" datatype

BED

<img width="502" alt="screen shot 2016-06-02 at 2 02 44 pm" src="https://cloud.githubusercontent.com/assets/8999735/15761066/200b1390-28cb-11e6-8aef-18f3b0f550cd.png">

<img width="591" alt="screen shot 2016-06-02 at 2 03 06 pm" src="https://cloud.githubusercontent.com/assets/8999735/15761070/24e09b38-28cb-11e6-9b5b-1b2c6d01d1be.png">

Yaml

<img width="501" alt="screen shot 2016-06-02 at 2 01 50 pm" src="https://cloud.githubusercontent.com/assets/8999735/15761083/331623ee-28cb-11e6-891e-99670524ddb9.png">

<img width="680" alt="screen shot 2016-06-02 at 2 02 11 pm" src="https://cloud.githubusercontent.com/assets/8999735/15761085/355609d0-28cb-11e6-90ee-f750e54b051d.png">

**Comment by jennaj** [comment]
Different error now. Config issue? Ping @natefoo @davebx @martenson 

Input is an upload BAM dataset, so sorted, and data size is ~ 4 GB. Due to data size, appears to be unrelated to the larger BAM files exceeding memory when upload or native sort tools are used.

> Fatal error: Exit code 134 ()
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  vector::_M_range_check
> /galaxy-repl/main/jobdir/XXX/XXX/XXX/tool_script.sh: line 9: 29474 Aborted                 (core dumped) bamtools conv

Retesting using direct sort in UI. If resolves, will update with that info.

**Comment by natefoo** [comment]
First one is out of memory, second one is unclear but I wouldn't be surprised if it was the same. Is this BAMTools or Picard SortSam? SortSam is allocated 16GB already. We really need to start using @erasche's Galactic Radio Telescope to write a proper dynamic rule for this.

**Comment by jennaj** [comment]
@natefoo The tool is NGS: BamTools > Convert, Merge, Randomize - the current version on main

**Comment by natefoo** [comment]
Sorry for my confusion. This tool is also allocated 16GB, however. Here's the breakdown of job states so it looks like about 9% are ending in error:

```sql
galaxy_main=> select count(state), state from job where tool_id like '%/bamtools/bamtools/%' group by state;
 count |        state         
-------+----------------------
    55 | paused
  2304 | deleted
 11281 | ok
     5 | new
  1347 | error
    41 | new_manually_dropped
(6 rows)
```

I've got to do something else at the moment but I should be able to come up with a query that compares the input sizes of successful jobs vs. error jobs.

**Comment by jennaj** [comment]
@natefoo I wonder if the errors are a combo: jobs that are "too large" +  jobs that used the two (out of seven) "convert to" types with problems. BED & YAML were the problems, the others worked fine. I am re-running a test with all convert to types to see if still localized. But with a very small BAM input/ref genome.

**Comment by jennaj** [comment]
@natefoo All conversions passed with three different BAM inputs. So - working now as far as this ticket goes (original issue). I am going to close it out - but would still be interesting to see why some jobs are failing and if different memory allocation would help.
