### ISSUE TITLE
VCF-VCFintersect needs to be updated in the Main Tool Shed and Galaxy Test/Main servers

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#391]
Update tool shed then update test/main to correct usage issues (tool always errors).

Error

> The Galaxy framework encountered the following error while attempting to run the tool:
> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
>     job_wrapper.prepare()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 897, in prepare
>     self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 445, in build
>     raise e
> ValueError: invalid literal for int() with base 10: 'use_adv_controls'
> Tool execution generated the following error message:
> invalid literal for int() with base 10: 'use_adv_controls'

Github master: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/vcflib/vcfvcfintersect

Tool Shed repo: https://toolshed.g2.bx.psu.edu/repository?repository_id=fde54b460b1ce65c

Change from July that addresses the "use_adv_controls" code problem: https://github.com/galaxyproject/tools-devteam/commit/4cb83fa3d4c009796d9b87557d17a89f0148889d

Report at Biostars: https://biostar.usegalaxy.org/p/19440/

**Comment by martenson** [comment]
I pushed the whole updated Conda-only vcflib to the MTS

**Comment by martenson** [comment]
@natefoo do I need to do something special to update all of these on Main given it needs Conda to install its dependency?

**Comment by natefoo** [comment]
@martenson Can the suite be updated so I don't have to update each tool individually? Or would that not work for updates anyway?

**Comment by martenson** [comment]
@natefoo here you go, install this one: https://toolshed.g2.bx.psu.edu/view/devteam/suite_vcflib_1_0_0_rc1/2cafd05a4a59

**Comment by martenson** [comment]
@natefoo do not install yet, there is no Conda package for one of the dependencies yet

**Comment by martenson** [comment]
@natefoo the suite should be fixed now and ready to install via Conda

**Comment by natefoo** [comment]
Looks like they installed correctly, but the version string was bad for vcfsort:

```
galaxy.tools.toolbox.base DEBUG 2016-09-30 17:45:01,532 Loaded tool id: toolshed.g2.bx.psu.edu/repos/devteam/vcfsort/vcfsort/@WRAPPER_VERSION@.0, version: @WRAPPER_VERSION@.0 into tool panel.
```

I have left the CVMFS transaction open so that if I should fix this manually I can do so, or just abort the transaction and start a new one once it's fixed.

**Comment by jennaj** [comment]
@martenson @natefoo ready to test or still undergoing changes?

**Comment by natefoo** [comment]
@jennaj No, the updates are not live in Main yet.

**Comment by martenson** [comment]
@natefoo that is an unexpanded macro token... no idea why that would happen. ping @bgruening @nsoranzo

**Comment by natefoo** [comment]
@martenson I found the problem - macros weren't included.

**Comment by martenson** [comment]
@natefoo well played!

**Comment by jennaj** [comment]
@natefoo @martenson Test started

**Comment by natefoo** [comment]
They were on Main, however they were not working due to a problem with the new conda-installed dependencies. This was fixed by switching to the use of `--copy` when creating conda environments for job runs and the fixing of a bug with `--copy` in galaxyproject/galaxy#3008.

VCF-VCF Intersect is working for me now. Hopefully the other vcflib tools work as well.

**Comment by jennaj** [comment]
This is still failing for me in my test history. Trying another.

**Comment by natefoo** [comment]
@jennaj If you're using rerun, select the new version of the tool. The old one won't work (and we should probably remove it).

**Comment by jennaj** [comment]
@natefoo Yes, passes with wrapper v 1.0.0_rc1.0 - thanks!

**Comment by martenson** [comment]
splendid

**Comment by martenson** [comment]
@jennaj yeah, new ticket please

**Comment by jennaj** [comment]
Will do, thanks!

**Comment by jennaj** [comment]
Forgot to link ticket back. Testing it again, updates will go in there: https://github.com/galaxyproject/galaxy/issues/3021
