### ISSUE TITLE
MarkDuplicatesWithMateCigar problem with tool form option, impacts http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#401]
Is this the fix? Is the solution just to update Main or is more going on?
https://github.com/galaxyproject/tools-devteam/issues/150

**One version of the tool throws an error: Galaxy Version 1.126.0** 
- Related to COMMENTS. Known, fixed, but not updated at http://usegalaxy.org (?)
- Should we remove that version of the tool? If just hidden, jobs will fail, so is not useful as-is

*_Command-line example. Not available for this tool version :( *_ 

**Error**

> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/**init**.py", line 170, in prepare_job
>     job_wrapper.prepare()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/**init**.py", line 897, in prepare
>     self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 445, in build
>     raise e
> **NotFound: cannot find 'comments'**

**One version fails because a particular tool form value is not being parsed: Galaxy Version 1.136.0**
- This should be fixed
- Does not impact all jobs, is content dependent
- Might be related to other COMMENT fixes

**Bad option: MINIMUM_DISTANCE**

Changing the value changes the command line, but it doesn't change the error. **Problematic handling of the parameter?** Label on tool form: The minimum distance to buffer records to account for clipping on the 5' end of the records

**Command-line example. Note how this also is related to COMMENTS.** 

> Job Command-Line: _JAVA_OPTIONS=${_JAVA_OPTIONS:-'-Xmx2048m -Xms256m'} && export _JAVA_OPTIONS && java -jar $JAVA_JAR_PATH/picard.jar MarkDuplicatesWithMateCigar INPUT="/galaxy-repl/main/files/017/489/dataset_17489083.dat" OUTPUT="/galaxy-repl/main/files/017/499/dataset_17499098.dat" METRICS_FILE="/galaxy-repl/main/files/017/499/dataset_17499097.dat" COMMENT="" **MINIMUM_DISTANCE="200"** SKIP_PAIRS_WITH_NO_MATE_CIGAR="true" REMOVE_DUPLICATES="false" ASSUME_SORTED="true" DUPLICATE_SCORING_STRATEGY="TOTAL_MAPPED_REFERENCE_LENGTH" READ_NAME_REGEX='[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).*.' OPTICAL_DUPLICATE_PIXEL_DISTANCE="100" BLOCK_SIZE=100000 VALIDATION_STRINGENCY="LENIENT" QUIET=true VERBOSITY=ERROR

**Error**

> Fatal error: Exit code 1 ()
> Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/scratch
> record #1: J00130:20:HCWN3BBXX:6:1202:18182:22766 89  1   12242   0   145M    =   12242   0   TGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCCGCAGCTGGACCCCTACCTGCCGTCTGCTGCCATCGGAACCCAAAGCCAGGCTGTGACTGCTCAGACCAGCCGGCTGGAGGGAGGGGCTCAGCAGGTCTGGCT   JJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA   X0:i:2  X1:i:4  MD:Z:42A37G9G54 RG:Z:1  XG:i:0  AM:i:0  NM:i:3  SM:i:0  XM:i:3  XO:i:0  XT:A:R
> record #2: J00130:20:HCWN3BBXX:5:2223:26727:14150 89  1   12243   0   39M =   12243   0   GCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCT FJJJFJJJFJJJFJ<JJ7JA-JJJJJJJJJFJJJFFAAA X0:i:6  X1:i:1  MD:Z:39 RG:Z:1  XG:i:0  AM:i:0  NM:i:0  SM:i:0  XM:i:0  XO:i:0  XT:A:R
> Exception in thread "main" picard.PicardException: Found a samRecordWithOrdinal with sufficiently large clipping that we may have
>  missed including it in an early duplicate marking iteration.  Please increase the minimum distance to at least 104bp
> to ensure it is considered (was 102).
> Record was: J00130:20:HCWN3BBXX:6:1202:18182:22766    89  1   12242   0   145M    =   12242   0   TGCTCATCTCCTTGGCTGTGATACGTGGCCGGCCCTCGCTCCCGCAGCTGGACCCCTACCTGCCGTCTGCTGCCATCGGAACCCAAAGCCAGGCTGTGACTGCTCAGACCAGCCGGCTGGAGGGAGGGGCTCAGCAGGTCTGGCT   JJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA   X0:i:2  X1:i:4  MD:Z:42A37G9G54 RG:Z:1  XG:i:0  AM:i:0  NM:i:3  SM:i:0  XM:i:3  XO:i:0  XT:A:R
> 
>   at picard.sam.markduplicates.MarkDuplicatesWithMateCigarIterator.checkForMinimumDistanceFailure(MarkDuplicatesWithMateCigarIterator.java:325)
>   at picard.sam.markduplicates.MarkDuplicatesWithMateCigarIterator.markDuplicatesAndGetTheNextAvailable(MarkDuplicatesWithMateCigarIterator.java:418)
>   at picard.sam.markduplicates.MarkDuplicatesWithMateCigarIterator.next(MarkDuplicatesWithMateCigarIterator.java:219)
>   at picard.sam.markduplicates.MarkDuplicatesWithMateCigarIterator.next(MarkDuplicatesWithMateCigarIterator.java:47)
>   at picard.sam.markduplicates.MarkDuplicatesWithMateCigar.doWork(MarkDuplicatesWithMateCigar.java:132)
>   at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)
>   at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:95)
>   at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:105)

Updated tool wrapper planned: https://github.com/galaxyproject/tools-devteam/issues/326

**Comment by natefoo** [comment]
The old version should probably be hidden (removing it outright is non-trivial since all the picard tools are in a single repo - however, it should be possible to remove it from `shed_tool_conf.xml`, right @marten?)

The new versions appears to be a tool problem. I don't think it's related to `COMMENT` (which is set to an empty string) but that the `MINIMUM_DISTANCE` argument is being ignored.

**Comment by jennaj** [comment]
@natefoo Thanks Nate and ping @galaxyproject/guac - tool needs fix ^^

**Comment by martenson** [comment]
sorry I missed this (that is not my handle @natefoo :) 

we should be able to just set hidden="true" in the shed_tool_conf, or is the goal to not have it accessible to rerun also? @jennaj

**Comment by natefoo** [comment]
I don't think the old version ever worked, @martenson.

**Comment by martenson** [comment]
@natefoo I see, then removing it from shed_tool_conf sounds like the best option

**Comment by jennaj** [comment]
Fixed in 1.136.0 and closing. Old version (1.126.0) still on main and in MTS. New ticket to track that is here: https://github.com/galaxyproject/tools-devteam/issues/462
