### ISSUE TITLE
BUG: Bowtie2 Read ID Auto-Assign fails for "Paired-end Dataset Collection"

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-devteam#403]
When attempting to automatically assigned Read Group parameters, Bowtie2 fails with the error: 

```
Error executing tool: 'Dataset collection has no element_identifier with key forward.'
```

**Comment by jennaj** [comment]
Is this still open? Should I test or is it resolved?

**Comment by lparsons** [comment]
Good question, I haven't tried this in a long time (mostly gave up on paired-end collections due to bugs).

**Comment by nsoranzo** [comment]
I've added a basic test on paired collection in https://github.com/galaxyproject/tools-iuc/pull/1571 , also manually read group seemed to work in a small test I did. Closing, feel free to reopen if needed.
