### ISSUE TITLE
SamToFastq does not list fastqsanger output datasets in Workflow editor

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#414]
**Tool**

SamToFastq (Galaxy Version 1.136.0)

**Example history**

All outputs from the tool are of the datatype "fastqsanger" in the history - except for the hidden "txt" dataset/report that describes if BAM or SAM was input.

https://usegalaxy.org/u/jen/h/check-output-datatype-samtofastq-galaxy-version-11360

**Example workflow extracted from history above** 

Note the single "txt" output and that a noodle cannot connect to tools expecting a fastq input dataset. 

https://usegalaxy.org/u/jen/w/workflow-constructed-from-history-check-output-datatype-samtofastq-galaxy-version-11360

Reported at https://biostar.usegalaxy.org/p/20308

Ping @galaxyproject/guac

**Comment by natefoo** [comment]
That's because this tool uses output dataset discovery (the outputs are unknown until after the tool is run). I don't think there's any way around this currently for workflows but @galaxyproject/iuc might be able to say more on whether this tool could be written differently with a defined output.

**Comment by tshtatland** [comment]
For me and most of our users, having this tool in a workflow so that its output (fastq) serves as input for subsequent tools is the most common use case. We rarely use the fastq output of this tool as the final result. So the old tool version will remain my workaround, until there is a better one.

**Comment by lparsons** [comment]
My suggestion for something like this would be to create a collection, which can then be consumed in workflows. See my [fastx_barcode_splitter_enhanced](https://github.com/lparsons/galaxy_tools/tree/master/tools/fastx_barcode_splitter_enhanced) for an example.

**Comment by nsoranzo** [comment]
@tshtatland You may try to use this other tool for your use case:  https://toolshed.g2.bx.psu.edu/view/iuc/bedtools/

**Comment by jennaj** [comment]
For some reason, I was still tracking this as an open issue, then saw was really still open.

I'll retest using the existing test history/workflow and if a pass, close this out. With both the samtools and bedtools tools (latest versions, many changes have been made since 2016, to Galaxy and these tool suites).

@tshtatland Have you already tried this? Did it work? The tool at usegalaxy.org is in the **BEDtools** tool group named "Convert from BAM to FastQ". At usegalaxy.eu, the same tool is in the group **Operate on Genomic Intervals**. SamToFastq is in the group Picard on both servers. Just curious, as some downstream tools can be more picky about noodle connections/accepted input datatypes.

**Comment by tshtatland** [comment]
Thank you for everyone's suggestions! At the time I reported this issue, I ended up using the old SamToFastQ tool version. Today, I retested in a new workflow on usegalaxy.org. A workflow with a collection of bam files, then Convert from BAM to FastQ (Galaxy Version 2.27.0.0), followed by bowtie2, can all be connected as desired. Note that for Convert from BAM to FastQ, one needs to change data type for both read1 and read 2 to fastqsanger so that bowtie2 accepts it. Thank you for the follow up!

**Comment by jennaj** [comment]
Closing - SamToFastq now outputs fastqsanger output

Galaxy Tool ID: | toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_SamToFastq/2.7.1.0
Galaxy Tool Version: | 2.7.1.0

Test history: https://usegalaxy.org/u/jen/h/test-datatype-sam-to-fastq
