### ISSUE TITLE
Latest freebayes cannot use list collection

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/tools-devteam#429]
I upgrade to the latest freebayes and looks like it cannot handle correctly a list collection of bam files.

When I pass a list collection of bams either thru a workflow or the new GUI front end, the result is always just a single bam being executed. In the workflow editor , it will not acknowledged its a collection at all.  
I.e:
http://imgur.com/vOaSlYq 

Hope this regression is just freebayes. 
FYI the input for bam parameter is set to multiple="True"

https://github.com/galaxyproject/tools-devteam/blob/master/tools/freebayes/freebayes.xml#L279

**Comment by Takadonet** [comment]
anyone else ran into this issue?

**Comment by nsoranzo** [comment]
I think what you are seeing is that FreeBayes is run on all BAM datasets together at the same time, resulting in only 1 VCF output. That's been done on purpose (and it's the reason for the `multiple="True"` in the `<param>`).

**Comment by Takadonet** [comment]
So if I have a list collection where every entry is different sample and want to run all of them in parallel with a single click, it is not possible to use this Freebayes version?

**Comment by nsoranzo** [comment]
@jmchilton Any idea?

**Comment by jmchilton** [comment]
Same conversation we had on bamtools filter but in reverse - see https://github.com/galaxyproject/tools-devteam/pull/467#issuecomment-300293062. Galaxy should be able to map or reduce or multiple data parameters - but right now it can only reduce. If we want to be able to do mapping also within the currently framework limitations - there needs to be a conditional (select one dataset vs. select many datasets).

**Comment by Takadonet** [comment]
That probably be the best solution in the long term. Since most if not all my users want to map and not reduce, I think might just take out `multiple="True"` and import into our private toolshed till its fixed.

**Comment by bernt-matthias** [comment]
fixed by https://github.com/galaxyproject/tools-iuc/pull/1328
