### ISSUE TITLE
package_bowtie_2_2_4 name is confusing

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/tools-devteam#44]
Packages presently on the ToolShed:

package_bowtie_0_12_7	 (devteam)
package_bowtie_1_0_0 (iuc)
package_bowtie2_2_1_0	 (devteam)
package_bowtie_2_2_4 (devteam)

I think the latter should be renamed to package_bowtie2_2_2_4 for consistency and also because the package name specified inside tool_dependencies.xml is ```bowtie2```:

```
<package name="bowtie2" version="2.2.4">
```

**Comment by martenson** [comment]
The package was not renamed and stays as `package_bowtie_2_2_4 `.
Packages should be invisible to the large extent for the users and I feel this is not worth the renaming and reuploading hassle.
