### ISSUE TITLE
Tool directory variable in Python

### ISSUE THREAD

**Issue by CicoZhang** [galaxyproject/tools-devteam#457]
In my Python code, I have to use the full path to point to the executable file in the command, here is '/galaxy-central/tools/heinz/heinz-print', I know there is such a variable in xml file: $__tool_directory__/, is there a such one that can be used in python?

`    result = subprocess.run(args=['/galaxy-central/tools/heinz/heinz-print', args.nodes, args.edges, '-FDR', str(args.fdr), '-a', str(args.alpha), '-lambda', str(args.lam)] ,stdout=subprocess.PIPE, stderr=subprocess.PIPE)
`

**Comment by nsoranzo** [comment]
@CicoZhang You can pass $tool_directory as a parameter from the XML command to your Python script. Please use the galaxy-dev mailing list for this questions.
