### ISSUE TITLE
Remove MarkDuplicatesWithMateCigar 1.126.0 from http://usegalaxy.org (and MTS?)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#462]
This tool version will always fail. Newer version 1.136.0 on Main and in MTS.

Should repo also be removed from MTS? This is why I put the ticket in this repo.

Related to this fix: https://github.com/galaxyproject/tools-devteam/issues/401

@natefoo @martenson

**Comment by martenson** [comment]
If the repo has newer version that works I do not think we want to remove the repository from MTS. Uninstalling from Main is probably a good idea though.

**Comment by nsoranzo** [comment]
I don't think it's actually possible to remove a repository version from a Tool Shed.

**Comment by martenson** [comment]
@nsoranzo Not painlessly. We can do some hg hacking but we do not want to I believe. Unless it is like super-malicious.

**Comment by jennaj** [comment]
Thanks for feedback. Closing! :)
