### ISSUE TITLE
Test sqlite file does not create gene expression plots or heat maps in galaxy

### ISSUE THREAD

**Issue by hershbc** [galaxyproject/tools-devteam#465]
Hello,
I've been struggling to use cummeRbund in galaxy for gene expression and heat map generation for my own data.  Assuming that something wasn't processed correctly, I went into the test folder here on github for the cummerbund wrapper and took the sqlite file and loaded it into galaxy.  cummeRbund still cannot create gene expression plots or heat maps because it does not find any gene_IDs.  I apologize if I am not using the tool correctly, but I would really like to be able to generate these figures.  Could someone please help me understand this? And perhaps provide a test file for me to use?  I have read every post on biostars about cummeRbund in galaxy and have not found an answer.  

<img width="917" alt="screen shot 2017-04-28 at 3 14 08 pm" src="https://cloud.githubusercontent.com/assets/24661085/25543638/5f524e16-2c25-11e7-8c16-c21efca97be2.png">

**Comment by jennaj** [comment]
Duplicate, see https://github.com/galaxyproject/tools-devteam/issues/340
