### ISSUE TITLE
bamtools_filter: tool doesn't allow filtering against XS-tag

### ISSUE THREAD

**Issue by NCEichner** [galaxyproject/tools-devteam#484]
Hi tools-devteam!
We would like to seperate the reads which map on "+" strand of the reference genome from these mapping on the "-" strand. This could be done effectively using the XS-tag generated by hisat2.
But filtering with the tag "XS:+" or "XS:-" in "bamtools_filter" always ends up in a bamfile with only header-data but no mapped reads. In the filter-script characters "+" or "-" are missing. 
So when I looked into the corresponding XML-file it seems that "+" and "-" are no valid input characters in filtering using tags.
So could you please add these characters in the next version of this tool?

**Comment by bgruening** [comment]
@NCEichner is this what you had in mind? https://github.com/galaxyproject/tools-iuc/pull/1457
Can you try this locally?

Thanks!

**Comment by NCEichner** [comment]
@bgruening:  Yes, this fix works fine for us!

Should the new chars also be added within the corresponding help in line #163?
I thought about changing the first sentence of the help-text into something like: 
"Values can be combined with >, <, =, and ! (not). You also can use + or -". 
The rest of the help-text beginning with "Tag name and its value (...)" could then stay as it is now. 

Afterwards this issue can be closed.

Many thanks and bye!

**Comment by bgruening** [comment]
Do you want to change this and get credits or should I do this?
Thanks for checking!

**Comment by bgruening** [comment]
I improved the help a little bit and will hopefully merge it soon. Thanks!
