### ISSUE TITLE
cufflinks gffread tool

### ISSUE THREAD

**Issue by jj-umn** [galaxyproject/tools-devteam#50]
Minnesota researchers want a galaxy tool for the cufflinks gffread command.  The tool is available currently from:  https://testtoolshed.g2.bx.psu.edu/view/jjohnson/gffread  

Would there be any interest in adding this in the devteam all_cufflinks_tool_suite?   
Or the IUC tools?

**Comment by martenson** [comment]
Hi JJ, 
I don't see a problem with that. Please propagate your tool to the main TS and I will then update the cufflinks suite to include it.

**Comment by jj-umn** [comment]
Should I add it to the devteam github page?

**Comment by martenson** [comment]
I think that we currently prefer people to maintain tools under their accounts, but we welcome any contribution so any way you choose is great.
If you want to transfer your tool under the devteam account please create a PR in this repo and we will review and merge it. Afterwards I will propagate it to the TS and update the suite.

**Comment by jmchilton** [comment]
Resolved with #51.
