### ISSUE TITLE
Annotate with DGI 0.1 -  silent tool error 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#504]
**MTS**: https://toolshed.g2.bx.psu.edu/view/devteam/dgidb_annotator/c5bb987015c5

**Error**: Tool does not pick up annotation for valid gene IDs, instead returns an empty green "success" dataset.

Will the tool be updated? (2014 was last update). Not sure if the configuration is the root issue or not (at https://usegalaxy.org), or if the DGI external site changed how the tool should do the query (impacts all usage, main or local, etc).

If we don't choose to update, should we remove it from public servers (including Main)? Only one bug report has been sent in about it in last 3+ years. 

@nekrut @davebx @natefoo

**Comment by jennaj** [comment]
The tool problem was reported at Biostars today https://biostar.usegalaxy.org/p/28304/

We don't have an updated version of that tutorial. Didn't get added to the fixathon -- no tag in this repo and doesn't have another usegalaxy.org-specific "update tool when fixed" type of ticket, since I wasn't sure if we would even keep it or not, but I could make one. Lmk.

ping @davebx @natefoo @nekrut

**Comment by lmarkal** [comment]
Hi Jen,
Thanks so much for following up on my tool error report. I am quite new to bioinformatics and all things coding. I appreciate the help and it will be fantastic if this got bumped up for a fix. It is such a great tool!
It seems the input data is fine; 
https://usegalaxy.org/datasets/bbd44e69cb8906b520445591926b9ebf/show_params
I think the problem may lie with the tool version? Thanks!
ping @davebx @natefoo @nekrut @jgoecks

**Comment by lmarkal** [comment]
Oops, you are already looking into that! 
![image](https://user-images.githubusercontent.com/22734660/41196571-da92ec2e-6c08-11e8-87aa-b9fbfa236b23.png)
My question answered! Hope for the fix!

**Comment by jennaj** [comment]
Still a problem -- needs priority set, and at a minimum, the duplicate tool panel display fixed at ORG.

**Comment by martenson** [comment]
as of the dups, these are two different tools, one is `2Fdgidb_annotator` and the other `2Fdgidb_annotate`

**Comment by jennaj** [comment]
The metadata looks wrong for these.

The MTS links from GUI for both point to a single MTS repo https://toolshed.g2.bx.psu.edu/view/devteam/dgidb_annotator/c5bb987015c5

There is no way to tell them apart unless you view each versions tool metadata there. They have different tool ids yet nest into the same MTS repo (? should that be possible ?). The dev repos are reported to be the same and appear to be the same wrapper in the tip files in the MTS. So, two versions with MTS repo metadata that doesn't match up. I'm not sure which is really the most current or "correct" but both fail to process proper inputs (format/content) and output an empty green dataset. The MTS repo dates are very close in time (about two weeks apart).

Not sure what the solution is .. except to find out which is correct, fix that one, or decide to drop the tool and not fix it. Looks like you and @jmchilton worked on this when we did all the tool migrations out of /galaxy and into the MTS. Perhaps something didn't parse out well during that processing? Duplicated migration?

Other ideas?

----

**Both have a tool form like:**

<img width="576" alt="screen shot 2018-10-26 at 3 19 13 pm" src="https://user-images.githubusercontent.com/8999735/47595080-4b055400-d933-11e8-8908-7d706c7246cd.png">

----

**Top level repo metadata for both is the same, too**

<img width="774" alt="screen shot 2018-10-26 at 3 46 24 pm" src="https://user-images.githubusercontent.com/8999735/47595706-848b8e80-d936-11e8-8925-b04803b20876.png">
<img width="764" alt="screen shot 2018-10-26 at 3 45 41 pm" src="https://user-images.githubusercontent.com/8999735/47595707-85242500-d936-11e8-827f-14cbe26162ba.png">



----

**Repo metadata for v2 dated 2014-02-25**

<img width="494" alt="screen shot 2018-10-26 at 3 17 01 pm" src="https://user-images.githubusercontent.com/8999735/47595081-4b055400-d933-11e8-9e58-6b06752c3fd9.png">

----

**Repo metadata for v3 dated 2014-03-07**

<img width="502" alt="screen shot 2018-10-26 at 3 16 22 pm" src="https://user-images.githubusercontent.com/8999735/47595082-4b055400-d933-11e8-9814-62a80fe9d4c3.png">

**Comment by martenson** [comment]
the tool id has changed in the most recent changeset (to `dgidb_annotate`). We can uninstall the old revision, but we cannot force them to merge given they have different IDs. 

As of the actual error, I am not familiar with the tool enough to say.

**Comment by jennaj** [comment]
Tool removed from tool panel. thanks @davebx
