### ISSUE TITLE
bx-python fails to install, tries to access /root/.config/pip

### ISSUE THREAD

**Issue by datakid** [galaxyproject/tools-devteam#512]
While trying to install `suite_gops_1_0` in Galaxy 18.05, I'm seeing a long list of packages with Installation Status of "Installed, missing tool dependencies" 

The first one I look in (base coverage) reports that `bx-python 0.7.1` wont install, with the following error:
```
The directory &#39;/root/.cache/pip/http&#39; or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo&#39;s -H flag. The directory &#39;/root/.cache/pip&#39; or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo&#39;s -H flag. Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: &#39;/root/.cache/pip/wheels/62/99/f6/ebf2c9db687084e9b86e7d5d6e4dac4e05388ef7591fdebe4d&#39; Consider using the `--user` option or check the permissions.Installed tool dependencies: bx-python
```
How do I fix this?

We run Galaxy as the user galaxy. /home/galaxy exists. I tried installing suite_gops_1_0 TTW without success. I am using the ephemeris/bioblend package to install it like:
```
[root] $ su - galaxy
[galaxy] cd /galaxy
[galaxy] source /modules/bin/bioblend/0.11.0/bin/activate
(0.11.0) [galaxy] shed-tools install --api_key "myKEYhere" --galaxy "http://localhost/galaxy/" --name suite_gops_1_0 --owner devteam --latest  --section_label "NGS TOOLSETS"
Storing log file in: /tmp/ephemeris_bkf_8dk7
(1/1) Installing repository suite_gops_1_0 from devteam to section "NGS TOOLSETS" at revision c82347870270 (TRT: 0:00:02.275084)
        repository suite_gops_1_0 installed successfully (in 0:03:48.323164) at revision c82347870270
Installed repositories (1): [('suite_gops_1_0', None)]
Skipped repositories (0): []
Errored repositories (0): []
All repositories have been installed.
Total run time: 0:03:50.598579
```

**Comment by datakid** [comment]
I am also interested that `suite_gops_1_0` is marked with Installation Status Installed/green, and there is nothing in the usually very accurate `Manage dependencies` despite `Manage Tools` reporting all the `suite_gops_1_0` as "Installed, missing tool dependencies"

**Comment by nsoranzo** [comment]
I think the suite may have installed old versions of some tool repositories, which predates the use of conda for dependencies. Can you check that all tool repositories are at their latest version?

**Comment by datakid** [comment]
Will it still work if they are at their latest version? I don't know Galaxy well - the versions are version  markers only, not "requirements.txt" style markers?

**Comment by bernt-matthias** [comment]
I guess this is deprecated. Reopen if needed.
