### ISSUE TITLE
"format" attribute of data param does not correctly constrain datasets

### ISSUE THREAD

**Issue by iodice** [galaxyproject/tools-devteam#519]
Our tool includes this param:

```
    <param name="bigwig_files" type="data" multiple="true" format="bigwig" label="Bigwig files:"
           help="Select the files to include.">
    </param>
```

This results in an input that can toggle between "multiple datasets" and "dataset collection". When "multiple datasets" is selected, the user is offered a dataset with the format "gtf", in addition to the datasets whose format is "bigwig".  

<img width="869" alt="param bug" src="https://user-images.githubusercontent.com/3791167/47526590-2bf0be80-d86e-11e8-8765-d377e459666c.png">

**Comment by iodice** [comment]
Forgive me if this is obvious, but the screen shot shows that a dataset named "53: Cufflinks on data 32: assembled transcripts" is offered as one of the choices in the param I'm talking about (whose label is "Bigwig files"), but the history shows that that dataset has a format of "gtf" rather than bigwig.

**Comment by bernt-matthias** [comment]
I think this is expected. Internally a gtf -> bigwig converter is called before the execution of the tool. You may notice an extra hidden dataset that is created. In recent Galaxy versions you can also see this in the tool form (the shown data set name in `... (as bigwig)`).
