### ISSUE TITLE
MarkDuplicatesWithMateCigar aborted with error

### ISSUE THREAD

**Issue by prishly** [galaxyproject/tools-devteam#520]
Hi!
My MarkDuplicatesWithMateCigar job on sorted bam ended with an error:
Fatal error: Exit code 1 () Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/jobdir/021/178/21178009/_job_tmp -Xmx7g -Xms256m 17:17:34.082 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/cvmfs/main.galaxyproject.org/d

I'm new to galaxy, search didn't help. I ran that tool on the same bam file locally though with picard, it threw errors requiring a greater minimum distance until I increased it to 300, then it was OK. But for galaxy version of the tool even 400 didn't help. 
Why this difference and what went wrong with my galaxy duplicate marking?

**Comment by bernt-matthias** [comment]
This tool is now part of the IUC tools collection. If still relevant reopen the issue over there.
