### ISSUE TITLE
Move galaxy_sequence_utilities to /legacy

### ISSUE THREAD

**Issue by ic4f** [galaxyproject/tools-devteam#522]
This is a reminder (to self! @ic4f) to retire galaxy_sequence_utilities in this repo as soon as it is merged into tools-iuc https://github.com/galaxyproject/tools-iuc/pull/2466

Related discussion: https://github.com/galaxyproject/tools-devteam/pull/521#issuecomment-503610087 (entire collection is being migrated, not just fastq_groomer)

**Comment by bernt-matthias** [comment]
fixed by galaxyproject/tools-iuc#2466

**Comment by ic4f** [comment]
@bernt-matthias thanks! Sorry - I forgot to close this one.
