### ISSUE TITLE
Filter FASTQ length filtering issue

### ISSUE THREAD

**Issue by stalekar** [galaxyproject/tools-devteam#528]
It seems like the tool Filter FASTQ reads by quality scores and length does not work properly. When I run it for read length filtering it looses the information about the specified size limits and executes job as they were set at 0 (default, no filtering).

**Comment by nsoranzo** [comment]
@stalekar I've transferred the issue to this repo, which is where the `fastq_filter` tool is developed.

Also, I've tried to reproduce the issue and both `Minimum size` and `Maximum size` seem to work for me.

**Comment by bernt-matthias** [comment]
Going to close this. 

@stalekar feel free to reopen if the problem still occurs.
