### ISSUE TITLE
Split gffread tool out from cufflinks and update

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-devteam#530]
The `gffread` tool in the cufflinks repository is quite useful on it's own. Right now, it installs using the conda `cufflinks` package, but for some reason that seems out of date. I've run into a few issues where the seemingly newer version in the [bioconda `gffread` package](https://bioconda.github.io/recipes/gffread/README.html) works better (*i.e.* correctly). I think simply updating it to the lastest version in that conda package would work, I don't think any changes to the wrapper are necessary (though there may be some new options we could expose).

**Comment by bernt-matthias** [comment]
I guess this is solved by https://github.com/galaxyproject/tools-iuc/pull/2665
