### ISSUE TITLE
Fasta filer by length fails when max_length !=0

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/tools-devteam#536]
Issue reported by end user that they could not filter out large contigs from their fasta.  They had a contig file with 2 contigs over 2Mbp and remaining under 50kbp . When values were set to the following:

![contigs](https://user-images.githubusercontent.com/64732/70344099-7d63cf00-181e-11ea-81b8-2a8d6d0d38ce.png)

All contigs were filtered **in**.

Looks like the issue is that we have a[ 'one off' error](https://github.com/phac-nml/tools-devteam/blob/master/tools/fasta_filter_by_length/fasta_filter_by_length.py#L41) where tmp_size will stop counting when over max_length but not when it's equal. Hence if your maximum length is evenly divisible by the line length of your fasta record, it will always filter in!

**Comment by bernt-matthias** [comment]
Seems fixed.
