### ISSUE TITLE
Annovar from devteam is not Python3 compatible

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#539]
MTS: https://toolshed.g2.bx.psu.edu/view/devteam/table_annovar/08b003ee9db7

It looks like a 1-2 line fixup. Then update MTS. Then deploy on Main. 

Keep version at 0.2 or bump if it is rewritten to work with both Py2 + Py3?

>   File "/galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/table_annovar/9c75a9b5ecd2/table_annovar/replace_NA.py", line 82
>     print SEPARATOR.join(fields)
>                   ^
> SyntaxError: invalid syntax

Tool is failing at usegalaxy.org. Ping @davebx @mvdbeek 

ps: When updating the MTS, also fix the repo link, has unexpected content, breaking the URL

> Development repository: **None**https://github.com/galaxyproject/tools-devteam/tree/master/tools/table_annovar

**Comment by bernt-matthias** [comment]
Fixed in https://github.com/galaxyproject/tools-devteam/commit/699d1afda29ecea2ceef62fdfce4d813ea0fa7f2
