### ISSUE TITLE
GATK 1.4 tools need to be run in a Py2 environment (all)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#546]
MTS: https://toolshed.g2.bx.psu.edu/view/devteam/suite_gatk_1_4/3e6a4fcbf335

ping @mvdbeek @natefoo

**Comment by bernt-matthias** [comment]
Also there seems to be no conda package for version 1.4. (which is horribly outdated?) ..

**Comment by nekrut** [comment]
we've been talking about getting rid of it for a long time ... there is
absolutely no reason to maintain this

Anton Nekrutenko
Professor of Biochemistry
and Molecular Biology
Penn State University
*http://nekrut.bx.psu.edu <http://nekrut.bx.psu.edu>*
(814) 826-9628
