### ISSUE TITLE
Error while running gffread.

### ISSUE THREAD

**Issue by ambarishK** [galaxyproject/tools-devteam#556]
Sir, I am converting merged gtf files using gffread but it is not generating output.

````
0 bytes
formatfastadatabase?
No fasta index found for genomeref.fa. Rebuilding, please wait..
Fasta index rebuilt.

````

**Comment by bernt-matthias** [comment]
gffread is part of IUC (https://github.com/galaxyproject/tools-iuc/tree/master/tools/gffread). Would you be so nice to report the issue there (please also include more information like input file or used parameters).
