### ISSUE TITLE
change_case tool omits header?

### ISSUE THREAD

**Issue by AjitPS** [galaxyproject/tools-devteam#557]
Hi, just using the `change_case` tool, works great but noticed it didn't keep my input file's custom `header` and reverted to using galaxy default 1,2,3 header for output file columns? wonder why this is defined so? thanks.

can we add params `format_source`=input to https://github.com/galaxyproject/tools-devteam/blob/master/tools/change_case/changeCase.xml?

**Comment by bernt-matthias** [comment]
Sounds like a good idea:
