### ISSUE TITLE
sam_merge.xml tool file references $JAVA_JAR_DIR not set by conda? 

### ISSUE THREAD

**Issue by edwardsnj** [galaxyproject/tools-devteam#571]
Now that the picard 1.56.0 dependency is satisfied by conda rather than the Galaxy package manager / tool shed, this variable does not appear to be set correctly when the sam_merge tool runs.

I hacked in a hard-coded path to /mnt/galaxy/tool_dependences/... to pick up the conda package path, but this is not the "right way to do it" I'm sure. 

I'm running GVL 4.4.0, Galaxy 18.05, on AWS via CloudLaunch 0.2. 

Thanks,

**Comment by bernt-matthias** [comment]
You should use this tool: https://github.com/galaxyproject/tools-iuc/blob/master/tools/picard/picard_MergeSamFiles.xml 

I'm going to deprecate this tool.
