### ISSUE TITLE
Python 2 print statement in older tool -- could be more

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#604]
Fix or deprecate/remove?

- [ ]  tool_id=toolshed.g2.bx.psu.edu/repos/devteam/ucsc_custom_track/build_ucsc_custom_track_1/1.0.0
 * https://github.com/mvdbeek/usegalaxy-tests/issues/19
 * https://toolshed.g2.bx.psu.edu/repository?repository_id=fa77b14996785b05
 * https://github.com/galaxyproject/tools-devteam/tree/main/tools/ucsc_custom_track

**Comment by nsoranzo** [comment]
@jennaj This should be pretty easy to fix, if that's a tool that people still use. Just let me know what's the preferred option between fix and deprecate.

**Comment by jennaj** [comment]
Hi @nsoranzo 

Fixing it seems best if not too much trouble. Removing older tools always carries a risk of disappointing someone, or breaking an older workflow still out in the wild.

@bgruening did some magic to make it work at the EU server. Guessing it involved fixing up that print statement to be Py3 compatible, in their version (don't see any changes in the dev repo or toolshed).

If you could reference this issue in the PR, or post the PR back here, that would help link all together to make sure the update makes it out to the ORG server and into the `22.01` release (this tool is included as a default -- _I think_ but can confirm)

Thank you!

**Comment by bgruening** [comment]
I really just changed the print statements - there have been 2.
