### ISSUE TITLE
cuffmerge wrapper multi-select doesn't work with built-in genomes

### ISSUE THREAD

**Issue by najoshi** [galaxyproject/tools-devteam#63]
We run our own custom galaxy instance in the Amazon Cloud and I am updating our instance with the latest toolshed files. For cuffmerge, in past revisions, we would just have a button to add another GTF input. However, this latest one (10:b6e3849293b1) that has been replaced with a multi-select. We also have a few built-in genomes that we use with cuffmerge. When I choose the first GTF file (using locally cached sequence data) it will populate the reference genome correctly with our built-in genomes. However, once I choose more than one GTF file, I get one of two errors:

 No reference genome is available for the build associated with the selected input dataset
OR
 An invalid option was selected, please verify

The built-in genomes are definitely there and available for cuffmerge, and each of the GTF files have the correct database build associated with them, but for some reason choosing more than one GTF file in the multi-select causes an error. Is this a bug or am I doing something wrong?

- Nik.

**Comment by jmchilton** [comment]
Responded on `-dev` [here](http://dev.list.galaxyproject.org/problem-with-latest-toolshed-devteam-cuffmerge-wrapper-multi-select-td4666663.html).

**Comment by martenson** [comment]
This is most probably not tool-related. Please comment @najoshi if you think otherwise and I will re-open.
