### ISSUE TITLE
weblogo3 tool missing dependency on numpy

### ISSUE THREAD

**Issue by bcclaywell** [galaxyproject/tools-devteam#65]
The weblogo3 tool was failing for us, with the `rgWebLogo.py` wrapper reporting that weblogo was returning exit code 1. At the command line I duplicated the job environment and dependency shell commands and was able to reproduce the error:

```
## rgWebLogo3.py error - executing weblogo -F jpeg -c auto -o /home/galaxy/tmp/logo.jpg -U bits -t "test" -f /home/galaxy/tmp/test.fasta -s medium returned error code 1
## This may be a data problem or a tool dependency (weblogo) installation problem
## Please ensure weblogo is correctly installed and working on the command line -see http://code.google.com/p/weblogo
```

I then tried running the above weblogo command directly:

```
Traceback (most recent call last):
  File "/mnt/scdata/scdata_03/galaxy/containers/galaxy-qa/tool_deps/weblogo/3.3/devteam/package_weblogo_3_3/648e4b32f15c/weblogo", line 56, in <module>
    import weblogolib._cli
  File "/mnt/scdata/scdata_03/galaxy/containers/galaxy-qa/export/tool_deps/weblogo/3.3/devteam/package_weblogo_3_3/648e4b32f15c/weblogolib/__init__.py", line 108, in <module>
    from numpy import array, asarray, float64, ones, zeros, int32,all,any, shape
ImportError: No module named numpy
```

As a quick fix, I added a package dependency requirement for numpy to `rgWebLogo3.xml` and reloaded the tool in Galaxy, after which the tool worked properly.

**Comment by bgruening** [comment]
Brian; thanks for reporting. I pushed a fix, this will be included in the ToolShed as soon as possible.

**Comment by martenson** [comment]
updated in the Main TS: https://toolshed.g2.bx.psu.edu/view/devteam/weblogo3
