### ISSUE TITLE
Improved Read Group Handling

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/tools-devteam#92]
- BWA/BWA-mem should have an option to use collection information to assign read groups.
 - Bowtie2 should also have an option to use collection information to assign read groups.
 - [Tophat wrapper](https://github.com/galaxyproject/tools-devteam/blob/master/tools/tophat2/tophat2_wrapper.xml#L106) should be updated also. 
 - Picard AddOrReplaceReadGroups should have an option to use collection information to assign read groups.
 - There should be a tool to merge bams in such a way that collection information (sample name) is attached as read groups. (MergeSamFiles? MergeBamAlignment?)

**Comment by jmchilton** [comment]
Looks like this should be updated to include bowtie2 - my new plan is to create a macro file for read group handling that can be shared between bowite2, bwa, bwa-mem, and I guess other mappers to provide a uniform Galaxy interface - even if the actual command line interface is pretty different.

**Comment by bgruening** [comment]
Like it, we will probably break workflows but this seems to be worth it.

**Comment by jgoecks** [comment]
Tophat should be included in this update as well.

**Comment by jmchilton** [comment]
@jgoecks Added it - thanks!

@bgruening It won't break workflows - it will make upgrading them more difficult :).

**Comment by natefoo** [comment]
While we're (you're) at it, would a macro for the reference genome selector be possible? The format of that field varies somewhat over tools.

**Comment by bgruening** [comment]
I'm curious how you will manage this @jmchilton.
@natefoo back to my suggestion to collect such snippets separately and make them reusable components

**Comment by erasche** [comment]
So...a global macros.xml? yay! Finally!

**Comment by jmchilton** [comment]
@bgruening  My thinking is a macro file that is a library - https://github.com/galaxyproject/galaxy/compare/dev...jmchilton:readgroups?expand=1. I both proud and terrified by this - but if we ignore what is in the macro and just look at how tool authors will consume it - I don't think it is too bad.

As a tool consumer you will need to 
 - Copy of the macro file
 - Import it
 - Place either the conditional input set or unconditional list of inputs into your ``<inputs>``
 - Inject some stuff at the top of your command
 - Specify the input dataset, multiple input datasets, or input data collection that should be used to automate the specification of this stuff if the user wants to.
 - Inject another block into command that builds a bunch of variables ``$rg_id``, ``$rg_lb``, etc... 
 - Then build the command - there is even a little utility ``$format_read_group`` to help build different command line patterns - should cover a lot of scenarios and prevent the need for a big chain of `#if` .. ``#end if``s.

**Comment by jmchilton** [comment]
@erasche Still skeptical of the global macros - what is generally useful except the ``stdio`` tweak - and that should just be a flag ``<tool fail_reasonably="true">`` or something less snarky.

**Comment by erasche** [comment]
@jmchilton oh, okay, cool. (I have no horse in this race)

**Comment by bgruening** [comment]
@jmchilton can we close this one?

**Comment by jmchilton** [comment]
Sure - tophat still should be updated though.
