### ISSUE TITLE
Bowtie2: Mapping paired-dataset collections won't work...

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/tools-devteam#97]
... if also collecting unaligned reads.

https://github.com/bgruening/galaxytools/commit/982412eabf86fbd941d31242c3ab9fdaa6826225

**Comment by bgruening** [comment]
@jmchilton any progress here?

**Comment by jmchilton** [comment]
@bgruening Thanks for poking me on this - there are a couple of PRs to address this I think. I still don't like the output of the bowtie2 tool is uncollected - but there needs to be workflow nodes and history options for zipping and unzipping collections anyway - hopefully this use case can drive that.

**Comment by bgruening** [comment]
Yes, we need to have options to unzipp collections on every layer.
John I feel like we need urgently a way to bind a tool to a specific Galaxy version. Now that we have an API for the Galaxy version a simple tag like the following would be nice to have.
```
<requirements>
         <requirement type="package" version="7.221">mafft</requirement>
         <requirement type="galaxy" version="15.07"/>
</requirements>
```
Such tools should not appear in TS search or with a big warning.
Keep the patches coming, collections rock! But we need to tell admins to update Galaxy to get the latest tools.

**Comment by nsoranzo** [comment]
@bgruening :+1:
